public class MailsString {



    public static String mails = "260-1713351@ukwheutq.space\n" +
            "\n" +
            "260-1713351@usrowhmd.space\n" +
            "\n" +
            "accountant@chebawardacharlomanti.com\n" +
            "\n" +
            "accountant@d2.unadvised.store\n" +
            "\n" +
            "accountant@dis1.sunjiwoo.com\n" +
            "\n" +
            "accountant@dis2.sunjiwoo.com\n" +
            "\n" +
            "accountant@dis3.healthyideanest.com\n" +
            "\n" +
            "accountant@fitnesswellness.store\n" +
            "\n" +
            "accountant@ing2.goodvitalidea.com\n" +
            "\n" +
            "accountant@king1.healthyideanest.com\n" +
            "\n" +
            "accountant@l1.bereave.store\n" +
            "\n" +
            "accountant@l3.bereave.store\n" +
            "\n" +
            "accountant@let2.pisem.net\n" +
            "\n" +
            "accountant@let4.pisem.net\n" +
            "\n" +
            "accountant@m3.ambitiouss.store\n" +
            "\n" +
            "accountant@n2.adventurouss.store\n" +
            "\n" +
            "accountant@p1.disagreeable.co.uk\n" +
            "\n" +
            "accountant@s7.ww8.org\n" +
            "\n" +
            "admin@accudun.vestoval.site\n" +
            "\n" +
            "admin@acdvst2.gradeadvisors.com\n" +
            "\n" +
            "admin@acdvst4.gradeadvisors.com\n" +
            "\n" +
            "admin@acdvst5.gradeadvisors.com\n" +
            "\n" +
            "admin@adlines.shop\n" +
            "\n" +
            "admin@adopa2.embroiderywk.com\n" +
            "\n" +
            "admin@adopa4.embroiderywk.com\n" +
            "\n" +
            "admin@akqgusj.slimspirit.site\n" +
            "\n" +
            "admin@alkarama.live\n" +
            "\n" +
            "admin@aloebio.shop\n" +
            "\n" +
            "admin@astrologyserver.shop\n" +
            "\n" +
            "admin@augwatch.shop\n" +
            "\n" +
            "admin@berryandsunny.com\n" +
            "\n" +
            "admin@boosterest.life\n" +
            "\n" +
            "admin@break1.ddtsn.com\n" +
            "\n" +
            "admin@break2.daodanrensheng.com\n" +
            "\n" +
            "admin@breedbud.shop\n" +
            "\n" +
            "admin@buysuhagra.life\n" +
            "\n" +
            "admin@carffb.bigstty01.embroiderywk.net\n" +
            "\n" +
            "admin@cascadiacollege.live\n" +
            "\n" +
            "admin@celtic.cam\n" +
            "\n" +
            "admin@chinuch-lifelines.org\n" +
            "\n" +
            "admin@chipdid-et.site\n" +
            "\n" +
            "admin@cruhcc.top\n" +
            "\n" +
            "admin@cumqipwv.onlyyourfans.cam\n" +
            "\n" +
            "admin@djkhaled.cam\n" +
            "\n" +
            "admin@doxycyclinest.com\n" +
            "\n" +
            "admin@dsepxpy.usproviders.cam\n" +
            "\n" +
            "admin@duoduohuzhu.life\n" +
            "\n" +
            "admin@dutekcejqq.corporate-screening.com\n" +
            "\n" +
            "admin@ekmwkar.onlinesales.cam\n" +
            "\n" +
            "admin@exdynsrv.com\n" +
            "\n" +
            "admin@filmgratuithd.top\n" +
            "\n" +
            "admin@fisha.live\n" +
            "\n" +
            "admin@fugithevpt.onlyyourfans.cam\n" +
            "\n" +
            "admin@gbysk7.autosportsgarage.com\n" +
            "\n" +
            "admin@gddzsk9.autosportsgarage.com\n" +
            "\n" +
            "admin@goodayan.store\n" +
            "\n" +
            "admin@googbaby.shop\n" +
            "\n" +
            "admin@hauhstf.ghostdoggallery.com\n" +
            "\n" +
            "admin@hokiapel.shop\n" +
            "\n" +
            "admin@housesite.shop\n" +
            "\n" +
            "admin@hwxfvdn.virgenmediaa.com\n" +
            "\n" +
            "admin@iamchrislam.live\n" +
            "\n" +
            "admin@indiethon.live\n" +
            "\n" +
            "admin@jlsharing.com\n" +
            "\n" +
            "admin@juihhyss1.autosportsgarage.com\n" +
            "\n" +
            "admin@julian01.wortreise.net\n" +
            "\n" +
            "admin@julian04.wortreise.net\n" +
            "\n" +
            "admin@keyi.store\n" +
            "\n" +
            "admin@kilopa1.edistoriverridge.com\n" +
            "\n" +
            "admin@kopa2.edutech-int.com\n" +
            "\n" +
            "admin@lajpbye.2f11.com\n" +
            "\n" +
            "admin@lammuzo.commercegeek.info\n" +
            "\n" +
            "admin@layuu3.dfila.com\n" +
            "\n" +
            "admin@leadsboox.com\n" +
            "\n" +
            "admin@lkqrimz.silvapets.cam\n" +
            "\n" +
            "admin@lovenr.com\n" +
            "\n" +
            "admin@lovespells.top\n" +
            "\n" +
            "admin@lrzu2.dolikeu.com\n" +
            "\n" +
            "admin@lrzu3.dolikeu.com\n" +
            "\n" +
            "admin@macmedia.live\n" +
            "\n" +
            "admin@maxiaoque.com\n" +
            "\n" +
            "admin@mushiwx.top\n" +
            "\n" +
            "admin@mvwrips.coolgadgets.cam\n" +
            "\n" +
            "admin@nbkio.live\n" +
            "\n" +
            "admin@netstnes1.zhilvliang.com\n" +
            "\n" +
            "admin@netstnes2.zhilvliang.com\n" +
            "\n" +
            "admin@nihilxkxqf.doxycyclinest.org\n" +
            "\n" +
            "admin@nihilxkxqf.topruanjian.com\n" +
            "\n" +
            "admin@noumena.shop\n" +
            "\n" +
            "admin@oditrgiyh.onlyyourfans.cam\n" +
            "\n" +
            "admin@ogwjtpn.marketingworldsales.com\n" +
            "\n" +
            "admin@onlyyourfans.cam\n" +
            "\n" +
            "admin@pickme.live\n" +
            "\n" +
            "admin@producednarkorc.top\n" +
            "\n" +
            "admin@providentooall.evolvingtennessee.org\n" +
            "\n" +
            "admin@providentooall.lovenr.com\n" +
            "\n" +
            "admin@qiming.life\n" +
            "\n" +
            "admin@radiusfg.top\n" +
            "\n" +
            "admin@rajafreebet.me\n" +
            "\n" +
            "admin@raniglobal.shop\n" +
            "\n" +
            "admin@rerysk6.autosportsgarage.com\n" +
            "\n" +
            "admin@ringoforhomeless.life\n" +
            "\n" +
            "admin@sand-lounger.live\n" +
            "\n" +
            "admin@seasidesouls.top\n" +
            "\n" +
            "admin@sfterr10.simpelet3.com\n" +
            "\n" +
            "admin@sfterr8.simpelet3.com\n" +
            "\n" +
            "admin@shophouses.shop\n" +
            "\n" +
            "admin@skyart.me\n" +
            "\n" +
            "admin@slimfigga.life\n" +
            "\n" +
            "admin@snatchedishop.top\n" +
            "\n" +
            "admin@srisaipharma.life\n" +
            "\n" +
            "admin@staytu.com\n" +
            "\n" +
            "admin@stpatrickbotanica.live\n" +
            "\n" +
            "admin@tanshikebi.life\n" +
            "\n" +
            "admin@totamodtwr.lovenr.com\n" +
            "\n" +
            "admin@txhxotfy.fun\n" +
            "\n" +
            "admin@txvmcawy.space\n" +
            "\n" +
            "admin@unlessgoals.com\n" +
            "\n" +
            "admin@utxbfkj.buyclomid.life\n" +
            "\n" +
            "admin@uxbkxxo.takefreetrial.cam\n" +
            "\n" +
            "admin@velspsy.dodealsweb.com\n" +
            "\n" +
            "admin@voluptasajtnr.servicedu.cam\n" +
            "\n" +
            "admin@voluptasebecn.servicedu.cam\n" +
            "\n" +
            "admin@wang602.life\n" +
            "\n" +
            "admin@watozjx.webshoppnow.com\n" +
            "\n" +
            "admin@wawdttm.productsonweb.com\n" +
            "\n" +
            "admin@wnlv4dmax2.live\n" +
            "\n" +
            "admin@xjzhzaw.webshoppnow.com\n" +
            "\n" +
            "admin@zevhya1.csisce.com\n" +
            "\n" +
            "admin@zevhya2.csisce.com\n" +
            "\n" +
            "admin@zevhya3.csisce.com\n" +
            "\n" +
            "admin@zkuxpdvpop.hatfieldphilips.com\n" +
            "\n" +
            "admin@zszzvtb.redirectboss.com\n" +
            "\n" +
            "admin@zwbtoba.silvapets.cam\n" +
            "\n" +
            "admission@utulsa.edu\n" +
            "\n" +
            "admissions@northland.edu\n" +
            "\n" +
            "agus.tariansyah@pelindo.co.id\n" +
            "\n" +
            "amdqnkavvykdxppzbhgncqqmhicugzbjfvrhxwfzvkygrwvcwtmpkngjyqkwxqhwvrdwaixvmiirwpqfyfwqiijuf@ijrtipletcae.info\n" +
            "\n" +
            "annuity@ofefrsdtops.net\n" +
            "\n" +
            "annuity@plans-offers.com\n" +
            "\n" +
            "anzeghjaq@mailstreamuseastegress002.mxrecord.io\n" +
            "\n" +
            "apple@ofefrsdtops.net\n" +
            "\n" +
            "ashley@homesew.com\n" +
            "\n" +
            "atendimento@imigrantesbebidas.com.br\n" +
            "\n" +
            "ava@stoneforest.com\n" +
            "\n" +
            "bathtub@ofefrsdtops.net\n" +
            "\n" +
            "ben@benjaminhardy.com\n" +
            "\n" +
            "bennie-odom.2794@jonasoliver.monster\n" +
            "\n" +
            "billjones@sissyslogcabin.com\n" +
            "\n" +
            "bookings@azoresgetaways.com\n" +
            "\n" +
            "brandi-armstrong.3797@jonathanrias.fun\n" +
            "\n" +
            "bulten@e.goblen.com\n" +
            "\n" +
            "cat@catharinamaura.com\n" +
            "\n" +
            "catering@rootcellarchapelhill.com\n" +
            "\n" +
            "cea@mail.e.cea.com.br\n" +
            "\n" +
            "celina112022@outlook.com\n" +
            "\n" +
            "cknyfyhpxahputrkfmfdrqkkbvrpywuvupgcezxmeaeqjriyqjndmjdfyqfcemrnfivhqivifrbdfxzucmcuiaeqtkrqcbw@wviywacj.org.uk\n" +
            "\n" +
            "clientservicesmfl@maseratifl.com\n" +
            "\n" +
            "club@themenlohouse.com\n" +
            "\n" +
            "comercial@transcendentaltransportes.com.br\n" +
            "\n" +
            "communication@chestertownship.org\n" +
            "\n" +
            "communication@ocbsa.org\n" +
            "\n" +
            "communications@carrot-top.com\n" +
            "\n" +
            "comunicacao@e.ibmr.br\n" +
            "\n" +
            "comunicacao@e.uniritter.edu.br\n" +
            "\n" +
            "concierge@solidandstriped.com\n" +
            "\n" +
            "contact@barakatgallery.com\n" +
            "\n" +
            "contact@barnolakintopissdol.sbs\n" +
            "\n" +
            "contact@doyoueven.com\n" +
            "\n" +
            "contact@drool.pet\n" +
            "\n" +
            "contact@newsletter.hiddentonicformula.com\n" +
            "\n" +
            "contact@nuleafnaturals.com\n" +
            "\n" +
            "contact@pomalomkinkolamis.space\n" +
            "\n" +
            "contact@shopsocietysocial.com\n" +
            "\n" +
            "coop@ryder.com\n" +
            "\n" +
            "crew@hyperskill.org\n" +
            "\n" +
            "cs@reebok.ca\n" +
            "\n" +
            "csa@sunrisefarmvt.com\n" +
            "\n" +
            "cttehaeiacqwfauancyfawemrumewkdzwkzaxbcarkrtambvdkbadviffxvgvbmznvcfndwiiqvzakwjnqurbgdwurjrmtj@vpvytwre.org.uk\n" +
            "\n" +
            "customercare@nulastin.com\n" +
            "\n" +
            "customerservice@etaeproducts.com\n" +
            "\n" +
            "customerservice@inkedshop.com\n" +
            "\n" +
            "customerservice@quiltedtwins.com\n" +
            "\n" +
            "customersupport@thesfmarathon.com\n" +
            "\n" +
            "cwnhbsbsp@goodsurely.dynv6.net\n" +
            "\n" +
            "dcbritt@limestone.edu\n" +
            "\n" +
            "debra-ivy.2011@chandrarichards.monster\n" +
            "\n" +
            "dennis-brinson.3881@martycollins.hair\n" +
            "\n" +
            "deyffqhaop@whyixlzx.fun\n" +
            "\n" +
            "dkrmdjifntzwyxzmvvnekenmpvwnrdyuzrmzjvyvmdydpjypefjtnfxyivmreayrjechaftdzdutqvvbanqauvafpyagvzq@kxjtyyp.org.uk\n" +
            "\n" +
            "do-not-reply@aptdeco.com\n" +
            "\n" +
            "docmarty@martyrossmd.com\n" +
            "\n" +
            "donotreply-comm@jmpt.m.kckps.org\n" +
            "\n" +
            "donotreply@autismspeaks.org\n" +
            "\n" +
            "earrings@blomdahlusa.com\n" +
            "\n" +
            "ecommerce@rzmask.com\n" +
            "\n" +
            "ed@ofefrsdtops.net\n" +
            "\n" +
            "editor@msfocus.org\n" +
            "\n" +
            "efmichael4@outlook.com\n" +
            "\n" +
            "ehybvhclh@goodsurely.dynv6.net\n" +
            "\n" +
            "elizabeth-bowman.675@vyber.fun\n" +
            "\n" +
            "email@davidscottpeters.com\n" +
            "\n" +
            "email@fgqk.het.brown.edu\n" +
            "\n" +
            "email@mail.greensboro.com\n" +
            "\n" +
            "email@swagbucksemail.com\n" +
            "\n" +
            "emre@risein.com\n" +
            "\n" +
            "enews@cancerwa.asn.au\n" +
            "\n" +
            "enews@choicehomewarranty.com\n" +
            "\n" +
            "enews@pleasant.net\n" +
            "\n" +
            "espinaladler@elliman.com\n" +
            "\n" +
            "express@b.express.com\n" +
            "\n" +
            "facturacion@entrerios.net\n" +
            "\n" +
            "fam@immieats.com\n" +
            "\n" +
            "fedex@ofefrsdtops.net\n" +
            "\n" +
            "fordauthority@motrolix.com\n" +
            "\n" +
            "fqzgxnhktnyujvdamqzecmnhpfqmdduizztnzjurfzzpcijpydprjyjaxqpzpwgttdannwgeguqcizkmeqjfytmbizpkgbtmpt@ryixpcj.org.uk\n" +
            "\n" +
            "gunshows@crossroadsgunshows.com\n" +
            "\n" +
            "harbordelivery@qwiklabs-gcp-01-4ca194e0d27d.firebaseapp.com\n" +
            "\n" +
            "hello@eatfishwife.com\n" +
            "\n" +
            "hello@happytowander.com\n" +
            "\n" +
            "hello@postman.storyworth.com\n" +
            "\n" +
            "hello@rileyhome.com\n" +
            "\n" +
            "hello@trynood.com\n" +
            "\n" +
            "hello@wondermonday.com\n" +
            "\n" +
            "hello@zee-dog.com\n" +
            "\n" +
            "help@b.freshwap.co.in\n" +
            "\n" +
            "help@thetattoozoo.com\n" +
            "\n" +
            "henrybrooksbbda@royalpalmbeachcomber.pro\n" +
            "\n" +
            "hi@risewell.com\n" +
            "\n" +
            "hims@loopetest.online.com\n" +
            "\n" +
            "hjohnson@ncsheriffs.net\n" +
            "\n" +
            "hjweb@preservationvirginia.org\n" +
            "\n" +
            "home@ofefrsdtops.net\n" +
            "\n" +
            "homes@email.homes.com\n" +
            "\n" +
            "house@ofefrsdtops.net\n" +
            "\n" +
            "hrkqkytwtkqrztmdjwnahctbxdgikinccdrdkqnctinumijcfuzfeccpkjdhpuuwgnnvtbjgkpkrqexbcdnufyjyf@ggtjstyqtkzk.info\n" +
            "\n" +
            "ijvqnndeputfrxdzderqzrcrcbmxfqirbdqzbjdzythtrtnehftpwftxwrxxqzpdpdkjbmkzcdrukfrhryjvhreyntwaafmwwuimy@ktytkpyd.org.uk\n" +
            "\n" +
            "info@adoptagoldenknoxville.org\n" +
            "\n" +
            "info@aim.com.au\n" +
            "\n" +
            "info@andersonray.biz\n" +
            "\n" +
            "info@ap4.webtrendzz.co.in\n" +
            "\n" +
            "info@artavita.com\n" +
            "\n" +
            "info@articulatemusic.co.uk\n" +
            "\n" +
            "info@avowtexas.org\n" +
            "\n" +
            "info@barbellsandponytails.com\n" +
            "\n" +
            "info@bigarts.org\n" +
            "\n" +
            "info@bigtop.org\n" +
            "\n" +
            "info@blessthisstuff.com\n" +
            "\n" +
            "info@cbgbaseballcamps.com\n" +
            "\n" +
            "info@cvent.com\n" +
            "\n" +
            "info@demandprogress.org\n" +
            "\n" +
            "info@dgpilot.com\n" +
            "\n" +
            "info@drjudymorgan.com\n" +
            "\n" +
            "info@guardianbikes.com\n" +
            "\n" +
            "info@highscope.org\n" +
            "\n" +
            "info@hurricanewings.com\n" +
            "\n" +
            "info@idtag.com\n" +
            "\n" +
            "info@joxsox.com\n" +
            "\n" +
            "info@mauigold.com\n" +
            "\n" +
            "info@monroesportscenter.com\n" +
            "\n" +
            "info@muertoscoffeeco.com\n" +
            "\n" +
            "info@munkdebates.com\n" +
            "\n" +
            "info@mylacrossetournaments.com\n" +
            "\n" +
            "info@myramseyhotel.com\n" +
            "\n" +
            "info@prospertrading.com\n" +
            "\n" +
            "info@rbxactive.com\n" +
            "\n" +
            "info@recpro.com\n" +
            "\n" +
            "info@roundtoptexasantiques.com\n" +
            "\n" +
            "info@rvsnappad.com\n" +
            "\n" +
            "info@rwandarestored.org\n" +
            "\n" +
            "info@shirkphotography.com\n" +
            "\n" +
            "info@skincareessentials.com\n" +
            "\n" +
            "info@southcoastbotanicgarden.org\n" +
            "\n" +
            "info@spamanufacturers.com\n" +
            "\n" +
            "info@the-braid.org\n" +
            "\n" +
            "info@twobirdsoutdoors.com\n" +
            "\n" +
            "info@uniquecorals.com\n" +
            "\n" +
            "info@wildideabuffalo.com\n" +
            "\n" +
            "info@womaness.com\n" +
            "\n" +
            "info@yivo.org\n" +
            "\n" +
            "infolettres@latribune.ca\n" +
            "\n" +
            "inforeisen@secolkainas.onmicrosoft.com\n" +
            "\n" +
            "information@marketing1.marketstreetunited.com\n" +
            "\n" +
            "insider@cafezupas.com\n" +
            "\n" +
            "jaqimunkwtkhduntcruveaffqrunntmxmkxrfqhjzptcyjdiukxdexkjyrnmatrcrxyavfrfdaquzrqvwvicqhacjhfmgqa@vafeectc.org.uk\n" +
            "\n" +
            "jessica@newportlanding.com\n" +
            "\n" +
            "jimmy-rutland.548@maggiejackson.skin\n" +
            "\n" +
            "john@rhmserves.com\n" +
            "\n" +
            "journals@notification.elsevier.com\n" +
            "\n" +
            "jvffrbnakyztxkcmrcpcfcezjucimgdacgxgtqxurnuhfeyvvirvmnyitkjrjuxkxqybtjzjvgajjvaiuiehfeiwtwhtfcberj@zvjkbww.org.uk\n" +
            "\n" +
            "kbeywlxku7oxoiy4eovgtzd1u@alxobnpllolikolo123us.onmicrosoft.com\n" +
            "\n" +
            "keiqnom@priv8shop.com\n" +
            "\n" +
            "kelvin-chalifour.2093@marinatate.online\n" +
            "\n" +
            "kevin.ellis@bonecoach.com\n" +
            "\n" +
            "krissie@abettersolutionins.com\n" +
            "\n" +
            "lankybox@hellojuniper.com\n" +
            "\n" +
            "laura@rowdysprout.com\n" +
            "\n" +
            "leaffilter@loopetest.online.com\n" +
            "\n" +
            "leta-chastain.242@jenrf.fun\n" +
            "\n" +
            "letitia-ellington.251@loismccall.ink\n" +
            "\n" +
            "lillie-ortega.4833@noahgoodwin.shop\n" +
            "\n" +
            "lucasmooreffah@nuggetsvslakers.org\n" +
            "\n" +
            "mail@demirmedyamail6.com\n" +
            "\n" +
            "mailer-daemon@antispam-01.wavenet.com\n" +
            "\n" +
            "mailing@dayspring.com\n" +
            "\n" +
            "marketing@hammitt.com\n" +
            "\n" +
            "marketing@incrementaltools.com\n" +
            "\n" +
            "marketing@taotronics.com\n" +
            "\n" +
            "mary-ryan.2339@ralphsanford.site\n" +
            "\n" +
            "maryjanesfarm@maryjanesfarm.org\n" +
            "\n" +
            "meahelp@disneyplus.com\n" +
            "\n" +
            "medicareconnect@mpgus.com\n" +
            "\n" +
            "memberservices@freshpressedoliveoil.com\n" +
            "\n" +
            "membership@amateurgolf.com\n" +
            "\n" +
            "messages@fastmodelsports.com\n" +
            "\n" +
            "metamask@2fa.eth\n" +
            "\n" +
            "metoffice@service.govdelivery.com\n" +
            "\n" +
            "michael@faiberton.onmicrosoft.com\n" +
            "\n" +
            "microsoft365@engagement.microsoft.com\n" +
            "\n" +
            "microsoftstore@microsoftstoreemail.com\n" +
            "\n" +
            "mira@marthaswarehouse.com\n" +
            "\n" +
            "mkt@esquadgroup.com.br\n" +
            "\n" +
            "mvwhkvnejftcgktfctvhxrvymzcwtwcaezhujikzxfyabjiwvfaxzranmtvthfdqbbmzwjafgkzbebtuufmqbqrfqeabch@htgfmdui.org.uk\n" +
            "\n" +
            "mychart@urmedicine.org\n" +
            "\n" +
            "ndfkxnwtmqcxtfapdzmbarghnqeafpcaacydgipvwqvmwajzwqyvaypqjzuhxffehhqvcnutzbwfgxvajrvuhywainjnhiq@pwhpdtk.org.uk\n" +
            "\n" +
            "nespresso@email.nespresso.com\n" +
            "\n" +
            "netflix@membership-offers.com\n" +
            "\n" +
            "netflix@ofefrsdtops.net\n" +
            "\n" +
            "neuropathy@ofefrsdtops.net\n" +
            "\n" +
            "new-offer-id57953@maverickshuerta-tk0035.mom\n" +
            "\n" +
            "news@analytics.finchte.de\n" +
            "\n" +
            "news@booking.talinore.zone\n" +
            "\n" +
            "news@dexybok.store\n" +
            "\n" +
            "news@israelnationalnews.com\n" +
            "\n" +
            "news@nixybok.store\n" +
            "\n" +
            "news@zutano.com\n" +
            "\n" +
            "newsletter@email.scoutingwire.org\n" +
            "\n" +
            "newsletter@goldengatewinecellars.com\n" +
            "\n" +
            "newsletter@kcrw.pma117thannualconvention.com\n" +
            "\n" +
            "newsletter@sipalimafor.onmicrosoft.com\n" +
            "\n" +
            "newsletter@staygenerator.com\n" +
            "\n" +
            "newsletter@web1.regbro.co.in\n" +
            "\n" +
            "newsletter@wfsx.bcacs.org\n" +
            "\n" +
            "nidal@salehgroup.com\n" +
            "\n" +
            "no-reply@avoomobile.com\n" +
            "\n" +
            "no-reply@colourpop.com\n" +
            "\n" +
            "no-reply@daybook.com\n" +
            "\n" +
            "no-reply@gossby.com\n" +
            "\n" +
            "no-reply@nycballet.com\n" +
            "\n" +
            "no-reply@stamps.com\n" +
            "\n" +
            "no-reply@xw1g82z.onmicrosoft.com\n" +
            "\n" +
            "noreply-cards@talkhome.co.uk\n" +
            "\n" +
            "noreply.quote.thebikeinsurer.co.uk@comparisonexpert.co.uk\n" +
            "\n" +
            "noreply@annals.org\n" +
            "\n" +
            "noreply@flowershopnetwork.com\n" +
            "\n" +
            "noreply@helsyqfkbnqs.fyi\n" +
            "\n" +
            "noreply@hoyauicljtcx.online\n" +
            "\n" +
            "noreply@mysewnet.com\n" +
            "\n" +
            "noreply@oversixty.com.au\n" +
            "\n" +
            "noreply@pelicanparts.com\n" +
            "\n" +
            "noreply@portillos-hotdogs.com\n" +
            "\n" +
            "noreply@publishingconcepts.com\n" +
            "\n" +
            "noreply@shellpointmtg.com\n" +
            "\n" +
            "noreply@statista.com\n" +
            "\n" +
            "noreplycrowdhub@arise.com\n" +
            "\n" +
            "oavpzyuxf3dylsac6pbtwswd7z9fhxnexsamtz23wabrlljtm3lv0xkszb3hzk86dcsm9hsiecqjoiznqsptrtt@hyiltkzty.org.uk\n" +
            "\n" +
            "office@damalokaji64.onmicrosoft.com\n" +
            "\n" +
            "oksanaorender@gmail.com\n" +
            "\n" +
            "online@kenssewingcenter.com\n" +
            "\n" +
            "orlandovenues@cityoforlando.net\n" +
            "\n" +
            "ovpkwbmyc@goodsurely.dynv6.net\n" +
            "\n" +
            "ozchngg@onclickit.com\n" +
            "\n" +
            "patterns@lazygirldesigns.com\n" +
            "\n" +
            "paul-covey.1111@kathryowen.motorcycles\n" +
            "\n" +
            "peggy-wilson.6954@jazminmccullough.lol\n" +
            "\n" +
            "peggy@sewhouse7.com\n" +
            "\n" +
            "photojosh@expertphotography.com\n" +
            "\n" +
            "polar@loopetest.online.com\n" +
            "\n" +
            "postit@cordovacity.store\n" +
            "\n" +
            "product@risein.com\n" +
            "\n" +
            "protection@ofefrsdtops.net\n" +
            "\n" +
            "pvglxgzyw@goodsurely.dynv6.net\n" +
            "\n" +
            "qbtzvngrhtgweycbpujqbkexhzxbqtbkwatnkegidfwzbibvtbjixnkjhqhhdjdgdwqzamcuruyibtfgpftmjyekjxjdpng@ntnqucnj.org.uk\n" +
            "\n" +
            "qdzyapkqtm@uijvscfe.space\n" +
            "\n" +
            "qfwxdiz@touhidur.xyz\n" +
            "\n" +
            "qmvrwgwqeyqfubzgcybztvexpvrntydyqrycynfcfeuqnyhvzbaejgkegyrwnyuynwmkyrfuvumtqfgpamnrmerjkmranhp@vpvytwre.org.uk\n" +
            "\n" +
            "rachel-mason.3608@sarafigueroa.shop\n" +
            "\n" +
            "raul-montello.5592@isobelmcbride.cyou\n" +
            "\n" +
            "rebecca@bryanhousequilts.com\n" +
            "\n" +
            "reminder@hotmail.com\n" +
            "\n" +
            "renewal@ofefrsdtops.net\n" +
            "\n" +
            "reply@engage.minecraft.net\n" +
            "\n" +
            "reveal@the.homedoctorsecrets.com\n" +
            "\n" +
            "rewards@gigiscupcakesusa.com\n" +
            "\n" +
            "rjqxfxeqmmrtggyyzyfxfaexncyeumdjtpnherqijwthnennrqibmrfrtejwfvbereywkxaedzzrphgqugjkhzikahuivdhhzp@znuamzj.org.uk\n" +
            "\n" +
            "robert-spencer.9593@fanniemckinney.makeup\n" +
            "\n" +
            "roger-mccane.4085@ernharrington.website\n" +
            "\n" +
            "rose-sanders.878@audreydejesus.sbs\n" +
            "\n" +
            "roses@send.heirloomroses.com\n" +
            "\n" +
            "rudolph-cardenas.3835@halenimaloun.lol\n" +
            "\n" +
            "russel-smith.7664@andrewhunter.boats\n" +
            "\n" +
            "rxlocalsupport@rxlocal.com\n" +
            "\n" +
            "ryan@lovejoywellness.net\n" +
            "\n" +
            "saatva@ofefrsdtops.net\n" +
            "\n" +
            "sales@eyecatchingcoral.com\n" +
            "\n" +
            "sales@farmhouseismystyle.com\n" +
            "\n" +
            "sales@precisionreloading.com\n" +
            "\n" +
            "sales@seadwelling.com\n" +
            "\n" +
            "salvador-wolford.4058@kelleychung.site\n" +
            "\n" +
            "samiksha.singhseo@hotmail.com\n" +
            "\n" +
            "sarah@craftwithsarah.com\n" +
            "\n" +
            "sayhello@compendiuminc.com\n" +
            "\n" +
            "screening@ofefrsdtops.net\n" +
            "\n" +
            "serendipityzrljxqptnwvykom@outdoorsdelights.com\n" +
            "\n" +
            "service@2ndswing.com\n" +
            "\n" +
            "service@bellelily.com\n" +
            "\n" +
            "service@doffersted.store.com\n" +
            "\n" +
            "service@e.airportparkingreservations.com\n" +
            "\n" +
            "service@email.doterra.co.uk\n" +
            "\n" +
            "service@kerotin.com\n" +
            "\n" +
            "services@ruffhouzin.com\n" +
            "\n" +
            "shareefemad.mfqp@gmail.com\n" +
            "\n" +
            "shop@racexr.com\n" +
            "\n" +
            "shopgraceland@graceland.com\n" +
            "\n" +
            "siriusxm@ofefrsdtops.net\n" +
            "\n" +
            "smart@ofefrsdtops.net\n" +
            "\n" +
            "solaris@ofefrsdtops.net\n" +
            "\n" +
            "solutions@chronicle.com\n" +
            "\n" +
            "sony@email.sonyentertainmentnetwork.com\n" +
            "\n" +
            "specials@e.uline.com\n" +
            "\n" +
            "storage@ofefrsdtops.net\n" +
            "\n" +
            "store@message.scholastic.com\n" +
            "\n" +
            "stories@cikalomadiba04.onmicrosoft.com\n" +
            "\n" +
            "supply@ofefrsdtops.net\n" +
            "\n" +
            "support@chicwish.com\n" +
            "\n" +
            "support@classychargers.com\n" +
            "\n" +
            "support@doffersted.online.com\n" +
            "\n" +
            "support@doffersted.store.com\n" +
            "\n" +
            "support@drinktrade.com\n" +
            "\n" +
            "support@gochirp.com\n" +
            "\n" +
            "support@golfcartgarage.com\n" +
            "\n" +
            "support@golfknack.com\n" +
            "\n" +
            "support@joju.toribija.store\n" +
            "\n" +
            "support@leadsboox.com\n" +
            "\n" +
            "support@loopetest.online.com\n" +
            "\n" +
            "support@newzdeals.online.com\n" +
            "\n" +
            "support@ofefrsdtops.net\n" +
            "\n" +
            "support@ry2.haushaltsstrategie.com\n" +
            "\n" +
            "support@samplize.com\n" +
            "\n" +
            "support@skinsolutions.md\n" +
            "\n" +
            "support@sourceonedental.com\n" +
            "\n" +
            "support@therootcauseprotocol.com\n" +
            "\n" +
            "support@woolx.com\n" +
            "\n" +
            "supportdft@handcuffing.superintenden.com\n" +
            "\n" +
            "supportt@discover.superintenden.com\n" +
            "\n" +
            "supportt@posture.superintenden.com\n" +
            "\n" +
            "supporttv@posture.superintenden.com\n" +
            "\n" +
            "susie@busytoddler.com\n" +
            "\n" +
            "sybil-camp.8278@rodgerjensen.yachts\n" +
            "\n" +
            "talcum@ofefrsdtops.net\n" +
            "\n" +
            "team@mightypaw.com\n" +
            "\n" +
            "team@wd.wellnessdigest4u.com\n" +
            "\n" +
            "tickets@gpstpete.com\n" +
            "\n" +
            "today@republicannews.org\n" +
            "\n" +
            "totalinjuryhelp@ofefrsdtops.net\n" +
            "\n" +
            "tractor@ofefrsdtops.net\n" +
            "\n" +
            "tssupport@trunkshowstyle.com\n" +
            "\n" +
            "ucxjoyxzfqztohectdwyzmxtcbchadzopkcjiodiqqjxlfnwswsneaxidtrqqfhqdmhfutoyxjthnysxtwnqbejybvwdtd@qbmkfaaftkln.info\n" +
            "\n" +
            "upnpq5ig9hmgloi3mxgz1oqym@nqanqdbwgbluescorps.onmicrosoft.com\n" +
            "\n" +
            "usagealerts@duke-energyusagealert.com\n" +
            "\n" +
            "uyzppxiatkcfkqjvyucfvmwpcinvdtpfrygzfecujkydphkkwfengachgedzdedgfduyfrcuwzzwyqhgqdybzzgbmpew@qmvgczby.org.uk\n" +
            "\n" +
            "vanessa_ballester.54925@valreeves.lol\n" +
            "\n" +
            "veera@willhuntingtutoring.com\n" +
            "\n" +
            "vicky-wilson.8563@rinnoyer.hair\n" +
            "\n" +
            "vijay@rashmi.com\n" +
            "\n" +
            "vip@millionairestradingclub.com\n" +
            "\n" +
            "vjiwxdl5ymbmyyozhkklbecxj@fhcmlss5qdiyu67us.onmicrosoft.com\n" +
            "\n" +
            "yyicazbvdpgyetjtngumixyhjcbfihzdyrzndnaitwcdpqyvxbbttjjdhxgddzffaerfdhmbuikkgkvcmdkduxtwexuytyn@utyxaw.org.uk\n" +
            "\n" +
            "zantac@ofefrsdtops.net\n" +
            "\n" +
            "zdrukxfeecyqannujdzidxkvrhqiuftiajbmajbgnppyjxcruefuhawqpunbtbrckuvxkcexqpuigyrweheebnkieydqwe@qqkwoneo.org.uk\n" +
            "\n" +
            "zujjtwmru@pecrelay.telecompost.it\n" +
            "\n" +
            "yeshearing@leadsboox.com\n" +
            "\n" +
            "semaglutide@leadsboox.com\n" +
            "\n" +
            "camp@ofefrsdtops.net\n" +
            "\n" +
            "britebat@leadsboox.com\n" +
            "\n" +
            "spotify@leadsboox.com\n" +
            "endurance@leadsboox.com";
}
