import java.util.ArrayList;
import java.util.List;

public class Mails {
    public String[] mails = ("4caupbhnamechnj-earst-mqqkqsoanciimvm@lhdconsult.org\n" +
            "\n" +
            "61773158@61773158stoneridgefamilydentistry.com\n" +
            "\n" +
            "69983@69983netorgft4317129.onmicrosoft.com\n" +
            "\n" +
            "a6gt1dx5ddu4aueij0gd5mdyjvlkc0tnk0bcdju@janisch307.onmicrosoft.com\n" +
            "\n" +
            "aakanksha.singhseo@outlook.com\n" +
            "\n" +
            "acheuque@educarchile.cl\n" +
            "\n" +
            "admin@landlogisticsltd.com\n" +
            "\n" +
            "admin@onotherhappyday.com\n" +
            "\n" +
            "admin@ozy.com\n" +
            "\n" +
            "admin@wedge.net.in\n" +
            "\n" +
            "adoptionassistance-noreply@yahoogroups.com\n" +
            "\n" +
            "ae@e.aetv.com\n" +
            "\n" +
            "aghnubctxmnrfve-pbgzz-ckuazirgdqvxpat@soepatuhlah.com\n" +
            "\n" +
            "alanshearer9@alice.it\n" +
            "\n" +
            "alejandroandreboa@gmail.com\n" +
            "\n" +
            "alert@david36595.onmicrosoft.com\n" +
            "\n" +
            "allcarecp@outlook.com\n" +
            "\n" +
            "angie@navlogisticsinc.com\n" +
            "\n" +
            "anne@williamscorporation.co.nz\n" +
            "\n" +
            "arkeofili@substack.com\n" +
            "\n" +
            "auctions@strettons.co.uk\n" +
            "\n" +
            "bathandbodyworks@e2.bathandbodyworks.com\n" +
            "\n" +
            "bcmsg6sj78nct2v-4mhjbdisvgwv9no8@googlegroups.com\n" +
            "\n" +
            "beachcolony@santacruz136.onmicrosoft.com\n" +
            "\n" +
            "bid@sa.com\n" +
            "\n" +
            "bodybuilding@email.bodybuilding.com\n" +
            "\n" +
            "bradley.sams@email.opensourcetrades.com\n" +
            "\n" +
            "bulten@b.yurtdisiegitimhabercisi.com\n" +
            "\n" +
            "bulten@maximumbulten.com\n" +
            "\n" +
            "buqf0milf97meazszeyqdqoglvuxhszuy8a5amzf4o7jce3tgy-yjiine9zie6d@sweet.redapplemeter.com\n" +
            "\n" +
            "bycc@dickeys.com\n" +
            "\n" +
            "casting@wegotpop.com\n" +
            "\n" +
            "cduwk2ooaumtn1v-petgindm09jiu4wd6y@notifications.t-mobile.com\n" +
            "\n" +
            "cecila_cyphers320v03n@hotmail.com\n" +
            "\n" +
            "cefinox@orange.fr\n" +
            "\n" +
            "ceqtfze@email.pryomhb.org\n" +
            "\n" +
            "channel4@hi.channel4.com\n" +
            "\n" +
            "chat@nakedwines.com\n" +
            "\n" +
            "cissykarwowski1999@hotmail.com\n" +
            "\n" +
            "cititrends@cititrends.com\n" +
            "\n" +
            "ckiewel@bethlehemlutheran.org\n" +
            "\n" +
            "coingroup@savidlawrence.com\n" +
            "\n" +
            "concierge@ylang23.com\n" +
            "\n" +
            "confirmedpurchasestore-u2982hj18as-gd40g2sd1v@d40qw5d11.tamcjhauyfpalvnatfgjkg.com\n" +
            "\n" +
            "contact@campaigns.rnchq.com\n" +
            "\n" +
            "contact@communicationpromo.org.uk\n" +
            "\n" +
            "contact@incomestatementjournal.com\n" +
            "\n" +
            "contact@linandelle.com\n" +
            "\n" +
            "contact@marinasmirlo.co.uk\n" +
            "\n" +
            "contact@voluptatemltfid.ezabelpy.org.uk\n" +
            "\n" +
            "contacto@emilyschwab14.onmicrosoft.com\n" +
            "\n" +
            "contato@lut.com.br\n" +
            "\n" +
            "cs.9s6zbjlhrg9xndxx8xx94dme5kmo8wtgznk-yjou3t8waqja7igfk@emaildl.att-mail.com\n" +
            "\n" +
            "cs.av9cgkaxj3arcmqi4ddhdv2dvxxcvzxbt20-lea3lxpgskgiufaqs@emaildl.att-mail.com\n" +
            "\n" +
            "cs@email.quhh.org\n" +
            "\n" +
            "cs@email.rpep.org\n" +
            "\n" +
            "cs@email.vxer.org\n" +
            "\n" +
            "cs@email.zway.org\n" +
            "\n" +
            "csz4lpxqtiodwux-olihsrpdkvpejgro@firefoxgroups.com\n" +
            "\n" +
            "currentcatalog@aufeld9a.onmicrosoft.com\n" +
            "\n" +
            "customer.support@clothes2order.com\n" +
            "\n" +
            "customer_support@email.ticketmaster.com\n" +
            "\n" +
            "customercare@email.vioc.com\n" +
            "\n" +
            "customerservice0gvd@thymepeoria.com\n" +
            "\n" +
            "customerservice51sn7ehnfnpz@51sn7ehnfnpzconstructionreporter.com\n" +
            "\n" +
            "customerservice596324818754@596324818754squarespace.com\n" +
            "\n" +
            "customerservice5otisr63bjjz@5otisr63bjjzthesiliconreview.com\n" +
            "\n" +
            "customerservice6ut1pdvwmw7v@6ut1pdvwmw7vcapselectric.cl\n" +
            "\n" +
            "customerservice@abcstores.com\n" +
            "\n" +
            "customerservice@ameswalker.com\n" +
            "\n" +
            "customerservice@mbeans.com\n" +
            "\n" +
            "customerservice@simplesite.com\n" +
            "\n" +
            "customerservice@tfsnyc.com\n" +
            "\n" +
            "customerservice@ticwatches.co.uk\n" +
            "\n" +
            "customerservice@yarn.com\n" +
            "\n" +
            "customerservicebrdfpmzgst3t@sochware.com\n" +
            "\n" +
            "customerservicedxdn3idtvezw@noon.partners\n" +
            "\n" +
            "customerservicedxsqay0ieuxt@dxsqay0ieuxtcanastennis.com\n" +
            "\n" +
            "customerservicedydkuekd8txw@dydkuekd8txwfawnmontanye.com\n" +
            "\n" +
            "customerserviceee3vlt8zhjyn@laser-mayhem.com\n" +
            "\n" +
            "customerserviceesuagjqoortn@laser-mayhem.com\n" +
            "\n" +
            "customerserviceevgkfzhzstiuw@vxnugreensealsafety.com\n" +
            "\n" +
            "customerservicehvfidsg9jeav@h-is4.com\n" +
            "\n" +
            "customerservicej6psgywkbaiv@investing.com\n" +
            "\n" +
            "customerservicejfqxzmfajsrl@jfqxzmfajsrldeltatax.se\n" +
            "\n" +
            "customerservicejz27l0na3g6q@noon.partners\n" +
            "\n" +
            "customerservicek0zvdxf2l24p@k0zvdxf2l24pthekeeledeal.com\n" +
            "\n" +
            "customerservicemzjh@mzjhwparrishlaw.com\n" +
            "\n" +
            "customerservicenorgmrg6uu36@norgmrg6uu36stakspancakes.com\n" +
            "\n" +
            "customerservicep4y6rqz7dhl1@p4y6rqz7dhl1jbassdrop.com\n" +
            "\n" +
            "customerservicerjwe@rjwevincentetdussault.com\n" +
            "\n" +
            "customerservicerngo@rngodevroedtenthierry.com\n" +
            "\n" +
            "customerservicesdnc@sdnclcsmd.org\n" +
            "\n" +
            "customerserviceu8czxurdn2yb@u8czxurdn2ybthesiliconreview.com\n" +
            "\n" +
            "customerserviceuadf63a5m8cr@uadf63a5m8crmmhconsulting.net\n" +
            "\n" +
            "customerservicew1x2dbcjahmn@w1x2dbcjahmnwsimg.com\n" +
            "\n" +
            "customerservicewcab@wcaballtechcomm.net\n" +
            "\n" +
            "customerservicexggm1gv1gvex@acclaimshop.com.au\n" +
            "\n" +
            "customerservicexgipvhjibpsa@xgipvhjibpsagroomfield.co.uk\n" +
            "\n" +
            "customerservicezla8n1m0aoym@laser-mayhem.com\n" +
            "\n" +
            "czpjbzd@email.yxkqstp.org\n" +
            "\n" +
            "daivik@seosmoppc.net\n" +
            "\n" +
            "dallas@well.com\n" +
            "\n" +
            "dalnyywr3b7qszg-52rgorlawn1tbccl@googlegroups.com\n" +
            "\n" +
            "dannyd@cleanitsupply.com\n" +
            "\n" +
            "das3etaypacddigooepd-ynnqxdpmv663@hatchiokay.eu\n" +
            "\n" +
            "data-delivery-id205943781@mail.klicksend.com.br\n" +
            "\n" +
            "depelu.management@gmail.com\n" +
            "\n" +
            "doe@prasarana.com.my\n" +
            "\n" +
            "douglas54jzxyzwlwe7vgq6upged8owz78az3@vybo4pxiqlwk.com\n" +
            "\n" +
            "dsg@e.dcsg.com\n" +
            "\n" +
            "durex@e.durex.com\n" +
            "\n" +
            "elizabeth@email.flounderspecial.com\n" +
            "\n" +
            "elm@email.cbvizuo.org\n" +
            "\n" +
            "elm@email.fhbvlqc.org\n" +
            "\n" +
            "elm@email.jgdeslk.org\n" +
            "\n" +
            "elm@email.jjvtmhk.org\n" +
            "\n" +
            "elm@email.jnbnneo.org\n" +
            "\n" +
            "elm@email.nygjlsu.org\n" +
            "\n" +
            "elm@email.vhapkds.org\n" +
            "\n" +
            "elm@email.zreaxfp.org\n" +
            "\n" +
            "email@burtscher040.onmicrosoft.com\n" +
            "\n" +
            "email@e.krogermail.com\n" +
            "\n" +
            "email@service.marksandspencer.com\n" +
            "\n" +
            "email@winnrich.onmicrosoft.com\n" +
            "\n" +
            "emailaftrbfo@zm3dk.onmicrosoft.com\n" +
            "\n" +
            "emailhjckyuw@4mqxwd.onmicrosoft.com\n" +
            "\n" +
            "emailqpmdjwv@6rjb5r.onmicrosoft.com\n" +
            "\n" +
            "emails@uritishmuseum.org\n" +
            "\n" +
            "emailznvdadx@4vdqls.onmicrosoft.com\n" +
            "\n" +
            "emarketing@e.netgear.com\n" +
            "\n" +
            "eservice@harlandclarke.com\n" +
            "\n" +
            "euna86liiuogycp-qemm7s2gxxdp4swn@googlegroups.com\n" +
            "\n" +
            "factorydirectcraft@factorydirectcraft.com\n" +
            "\n" +
            "fastdatingsupport@livehelpnow.net\n" +
            "\n" +
            "fjakvxjdjj@9v7f.greathearted.live\n" +
            "\n" +
            "flickrteam@arrow.flickr.com\n" +
            "\n" +
            "friends@email.christmascentral.com\n" +
            "\n" +
            "funships@carnivalcruiselineemail.com\n" +
            "\n" +
            "gaia@goto.gaia.com\n" +
            "\n" +
            "galls@salzbu6.onmicrosoft.com\n" +
            "\n" +
            "gfile@ha.com\n" +
            "\n" +
            "glvzlrk@email.ixceadw.org\n" +
            "\n" +
            "gwpkxbcouerbasciftjvzngwdvh@healthbia.co.uk\n" +
            "\n" +
            "haydene.dunn@kznhealth.gov.za\n" +
            "\n" +
            "helenvriniotis@processcomanagement.com\n" +
            "\n" +
            "hello70464@70464glowskinco.co\n" +
            "\n" +
            "hello@sundaycitizen.me\n" +
            "\n" +
            "hello@tortugabackpacks.com\n" +
            "\n" +
            "help+newsletter@eigenendf.onmicrosoft.com\n" +
            "\n" +
            "help@wiggle.com\n" +
            "\n" +
            "help@yutopilotapp.com\n" +
            "\n" +
            "hollister@kerstinziegler584.onmicrosoft.com\n" +
            "\n" +
            "icdtasaemarketing@imf.org\n" +
            "\n" +
            "igfmobb@email.cmljjav.org\n" +
            "\n" +
            "info.operationrescue@gmail.com\n" +
            "\n" +
            "info506464294@mailva.evite.com\n" +
            "\n" +
            "info@bbi-reizen.nl\n" +
            "\n" +
            "info@bc.adorama.com\n" +
            "\n" +
            "info@campingnavigator.com\n" +
            "\n" +
            "info@coolshoes.com\n" +
            "\n" +
            "info@democraticvoters.org\n" +
            "\n" +
            "info@e.araba.com\n" +
            "\n" +
            "info@email.sygic.com\n" +
            "\n" +
            "info@granddezign.com\n" +
            "\n" +
            "info@helmutritter63.onmicrosoft.com\n" +
            "\n" +
            "info@iceshaker.com\n" +
            "\n" +
            "info@janineschachner.onmicrosoft.com\n" +
            "\n" +
            "info@mail.vetsource.com\n" +
            "\n" +
            "info@mapmyfitness-t.messages4.com\n" +
            "\n" +
            "info@myiclubonline.com\n" +
            "\n" +
            "info@n.zavvi.com\n" +
            "\n" +
            "info@news.tactics.com\n" +
            "\n" +
            "info@peepconsulting.com\n" +
            "\n" +
            "info@riecastdepotshop.com\n" +
            "\n" +
            "info@selecthomewarranty.com\n" +
            "\n" +
            "info@sheabelpets.com\n" +
            "\n" +
            "info@staysure.co.uk\n" +
            "\n" +
            "info@steveweissmusic.com\n" +
            "\n" +
            "info@stringsandbeyond.com\n" +
            "\n" +
            "info@taxhelpoffer.com\n" +
            "\n" +
            "info@tennis-warehouse.com\n" +
            "\n" +
            "info@thewreathshop.com\n" +
            "\n" +
            "info@tulumba.com\n" +
            "\n" +
            "info@unipak.com.tr\n" +
            "\n" +
            "info@vlopaoit6ezmoptimusu.com\n" +
            "\n" +
            "info@vsg.wealthplus.online\n" +
            "\n" +
            "info@wandp.com\n" +
            "\n" +
            "info@willie.nl\n" +
            "\n" +
            "infoiighki@iighkiveritaspress.com\n" +
            "\n" +
            "infopboljwkhb5uo@grupocpc.ar\n" +
            "\n" +
            "infoswiifn@swiifnveritaspress.com\n" +
            "\n" +
            "ionusjc@email.mxgjzxh.org\n" +
            "\n" +
            "irs@service.govdelivery.com\n" +
            "\n" +
            "itworks@itworksglobal.com\n" +
            "\n" +
            "jim@primalsourcenews.com\n" +
            "\n" +
            "jonathans@mecloud.co.in\n" +
            "\n" +
            "joseph@thosecallaways.com\n" +
            "\n" +
            "jowdmreabb@wdauh.z2zk.strabometry.com\n" +
            "\n" +
            "joy@perryhealth.com\n" +
            "\n" +
            "junta@el-cascajal.com\n" +
            "\n" +
            "katiebwtg@bwtgaxconnect.com\n" +
            "\n" +
            "kevinbrightseo@outlook.com\n" +
            "\n" +
            "kgowmegokbenrhogiqwjem-flyov@flyov.update2291amazon.com\n" +
            "\n" +
            "kim@insanelygoodrecipes.com\n" +
            "\n" +
            "kodakmoments@emails.kodakmoments.com\n" +
            "\n" +
            "kuberatanu718gn@aol.com\n" +
            "\n" +
            "lh7fj7lsxkc7fks-gfaxhvw8noshr2f1@googlegroups.com\n" +
            "\n" +
            "lhizybpwwq@affj.dedition.co.uk\n" +
            "\n" +
            "madonna1958salsa2020finaly@speedsearch2u.co.uk\n" +
            "\n" +
            "mail@club-individual.co.uk\n" +
            "\n" +
            "mail@email.anmkp.org\n" +
            "\n" +
            "mail@email.awlbj.org\n" +
            "\n" +
            "mail@email.awlk.org\n" +
            "\n" +
            "mail@email.axhca.org\n" +
            "\n" +
            "mail@email.chej.org\n" +
            "\n" +
            "mail@email.dllhu.org\n" +
            "\n" +
            "mail@email.dtbed.org\n" +
            "\n" +
            "mail@email.dwte.org\n" +
            "\n" +
            "mail@email.dxkso.org\n" +
            "\n" +
            "mail@email.dxugu.org\n" +
            "\n" +
            "mail@email.egcrw.org\n" +
            "\n" +
            "mail@email.fgcsm.org\n" +
            "\n" +
            "mail@email.fxebm.org\n" +
            "\n" +
            "mail@email.gfaw.org\n" +
            "\n" +
            "mail@email.hyjck.org\n" +
            "\n" +
            "mail@email.jpfesur.org\n" +
            "\n" +
            "mail@email.kbfrb.org\n" +
            "\n" +
            "mail@email.kkdvh.org\n" +
            "\n" +
            "mail@email.kwyxz.org\n" +
            "\n" +
            "mail@email.ldrtl.org\n" +
            "\n" +
            "mail@email.ltaf.org\n" +
            "\n" +
            "mail@email.ltaukti.org\n" +
            "\n" +
            "mail@email.luvsypb.org\n" +
            "\n" +
            "mail@email.lywd.org\n" +
            "\n" +
            "mail@email.mdmoa.org\n" +
            "\n" +
            "mail@email.mhvjx.org\n" +
            "\n" +
            "mail@email.mlmkn.org\n" +
            "\n" +
            "mail@email.mnuy.org\n" +
            "\n" +
            "mail@email.nejn.org\n" +
            "\n" +
            "mail@email.nlflt.org\n" +
            "\n" +
            "mail@email.nskyg.org\n" +
            "\n" +
            "mail@email.nvnfp.org\n" +
            "\n" +
            "mail@email.ocnik.org\n" +
            "\n" +
            "mail@email.ogfyn.org\n" +
            "\n" +
            "mail@email.oqyyg.org\n" +
            "\n" +
            "mail@email.oyuzn.org\n" +
            "\n" +
            "mail@email.psgu.org\n" +
            "\n" +
            "mail@email.pzgsl.org\n" +
            "\n" +
            "mail@email.qcxey.org\n" +
            "\n" +
            "mail@email.qsmaa.org\n" +
            "\n" +
            "mail@email.rekl.org\n" +
            "\n" +
            "mail@email.rsctc.org\n" +
            "\n" +
            "mail@email.sfygs.org\n" +
            "\n" +
            "mail@email.sipi.org\n" +
            "\n" +
            "mail@email.sqkw.org\n" +
            "\n" +
            "mail@email.srjp.org\n" +
            "\n" +
            "mail@email.tjzm.org\n" +
            "\n" +
            "mail@email.tlqzc.org\n" +
            "\n" +
            "mail@email.txcwj.org\n" +
            "\n" +
            "mail@email.uitz.org\n" +
            "\n" +
            "mail@email.utyyqax.org\n" +
            "\n" +
            "mail@email.vdyw.org\n" +
            "\n" +
            "mail@email.vmsshis.org\n" +
            "\n" +
            "mail@email.vnupe.org\n" +
            "\n" +
            "mail@email.vqqw.org\n" +
            "\n" +
            "mail@email.vrlbtta.org\n" +
            "\n" +
            "mail@email.vvqdm.org\n" +
            "\n" +
            "mail@email.wfkc.org\n" +
            "\n" +
            "mail@email.wixcppu.org\n" +
            "\n" +
            "mail@email.xkas.org\n" +
            "\n" +
            "mail@email.yilisqt.org\n" +
            "\n" +
            "mail@email.ypae.org\n" +
            "\n" +
            "mail@email.yvylg.org\n" +
            "\n" +
            "mail@email.znmvr.org\n" +
            "\n" +
            "mail@newsletter.fenviosmail.com\n" +
            "\n" +
            "mail@snusexpress.com\n" +
            "\n" +
            "mailers@muc-off.com\n" +
            "\n" +
            "marcelhasche@yahoo.com\n" +
            "\n" +
            "mark.mix@righttoworkfoundation.org\n" +
            "\n" +
            "marketing@baileyhydraulics.com\n" +
            "\n" +
            "marketing@bramco.com\n" +
            "\n" +
            "marketing@dynatrap.com\n" +
            "\n" +
            "marketing@epicevents.be\n" +
            "\n" +
            "members@mondosweeps.com\n" +
            "\n" +
            "meshahumi@gmail.com\n" +
            "\n" +
            "microsoft365@email.microsoft365.com\n" +
            "\n" +
            "microsoftstore@microsoftstoreemail.com\n" +
            "\n" +
            "minnetonka.insider@minnetonkamocc.com\n" +
            "\n" +
            "mirror@betriebsdirektor.de\n" +
            "\n" +
            "mjxtrfe.jpgkaze@iebhxtqmhb.perrychristinejacobs.work\n" +
            "\n" +
            "morningwire@apnews.com\n" +
            "\n" +
            "mvzcjrf@email.doeyldj.org\n" +
            "\n" +
            "neckar@ha.com\n" +
            "\n" +
            "news.17vkmr@7vkmrbetsywells.com\n" +
            "\n" +
            "news.1awdt@awdtulseaxconnect.com\n" +
            "\n" +
            "news.1deoo@deoorenewyoucompany.com\n" +
            "\n" +
            "news.1dvmy@nannews.ng\n" +
            "\n" +
            "news.1ehoy@ehoyulseaxconnect.com\n" +
            "\n" +
            "news.1fbec@fbecfreedomtrainforkids.com\n" +
            "\n" +
            "news.1gmvf@gmvfpanasiarelocations.in\n" +
            "\n" +
            "news.1gplz@gplzulseaxconnect.com\n" +
            "\n" +
            "news.1hsii@hsiiulseaxconnect.com\n" +
            "\n" +
            "news.1ipqo@ipqorenewyoucompany.com\n" +
            "\n" +
            "news.1jhmu@jhmupanasiarelocations.in\n" +
            "\n" +
            "news.1jmkv@jmkvfreedomtrainforkids.com\n" +
            "\n" +
            "news.1jvgi@nannews.ng\n" +
            "\n" +
            "news.1kbdn@kbdngreyhoundtavern.com\n" +
            "\n" +
            "news.1knb2drii0q79@knb2drii0q79valuedlives.co.uk\n" +
            "\n" +
            "news.1kuhx@kuhxpanasiarelocations.in\n" +
            "\n" +
            "news.1mhhd@mhhdtiroeng.co.za\n" +
            "\n" +
            "news.1muhc@muhcgotoguy.biz\n" +
            "\n" +
            "news.1ncom@ncomspg-realestate.com\n" +
            "\n" +
            "news.1obbb@obbbulseaxconnect.com\n" +
            "\n" +
            "news.1qrms@remove.bg\n" +
            "\n" +
            "news.1rggh@rgghretzkin.co.il\n" +
            "\n" +
            "news.1rjva@rjvafreedomtrainforkids.com\n" +
            "\n" +
            "news.1sigj@sigjfreedomtrainforkids.com\n" +
            "\n" +
            "news.1slvg@slvgulseaxconnect.com\n" +
            "\n" +
            "news.1uajm@uajmrenewyoucompany.com\n" +
            "\n" +
            "news.1uhdn@uhdnpanasiarelocations.in\n" +
            "\n" +
            "news.1wxju@wxjufreedomtrainforkids.com\n" +
            "\n" +
            "news.1wzfy@wzfyulseaxconnect.com\n" +
            "\n" +
            "news.1yenq@yenqulseaxconnect.com\n" +
            "\n" +
            "news.1zctf@zctfgreyhoundtavern.com\n" +
            "\n" +
            "news.1zpvc@zpvculseaxconnect.com\n" +
            "\n" +
            "news.all@accor-mail.com\n" +
            "\n" +
            "news@bjornborg.com\n" +
            "\n" +
            "news@culturanews.livrariacultura.com.br\n" +
            "\n" +
            "news@grandsierraresort.com\n" +
            "\n" +
            "news@news.3newslettercamping.com\n" +
            "\n" +
            "news@thecomfortcompany.com\n" +
            "\n" +
            "news@tiendeo.com\n" +
            "\n" +
            "newsletter-85f83701df68ace90dbafa8e362698a4@rachelwood1421.online\n" +
            "\n" +
            "newsletter@americanretirementinsider.com\n" +
            "\n" +
            "newsletter@e.reachplc.com\n" +
            "\n" +
            "newsletter@imwalking.de\n" +
            "\n" +
            "newsletter@lifetime-stocks.com\n" +
            "\n" +
            "newsletter@mail.allamericanpress.com\n" +
            "\n" +
            "newsletter@multi-meta.com\n" +
            "\n" +
            "newsletter@mychway.shop\n" +
            "\n" +
            "newsletter@newsletterin.com\n" +
            "\n" +
            "newsletter@onvitationinabottle.com\n" +
            "\n" +
            "newsletter@ott456.onmicrosoft.com\n" +
            "\n" +
            "newsletter@prtistcraftsman.com\n" +
            "\n" +
            "newsletter@rudeusa.com\n" +
            "\n" +
            "newsletter@rwgps.com\n" +
            "\n" +
            "newsletter@thinkurbytes.com\n" +
            "\n" +
            "newsletter@your.richusainvestor.com\n" +
            "\n" +
            "newsletters@email.familyhandyman.com\n" +
            "\n" +
            "newsletters@well.ca\n" +
            "\n" +
            "nike@vfficial.nike.com\n" +
            "\n" +
            "no-replies@enews.lakeside.com\n" +
            "\n" +
            "no-reply-maailbusiness-fhd02@fhd02.ku0wpeamazon.com\n" +
            "\n" +
            "no-reply@afetc.com\n" +
            "\n" +
            "no-reply@eclinicalmail.com\n" +
            "\n" +
            "no-reply@email.jumia.ma\n" +
            "\n" +
            "no-reply@emails.skechers.com\n" +
            "\n" +
            "no-reply@geni.com\n" +
            "\n" +
            "no-reply@mail.boots.com\n" +
            "\n" +
            "no-reply@mariesimon096.onmicrosoft.com\n" +
            "\n" +
            "no-reply@offers.vons.com\n" +
            "\n" +
            "no-reply@sharepointonline.com\n" +
            "\n" +
            "no-reply@ticwatches.co.uk\n" +
            "\n" +
            "no-reply@trinitymmj.com\n" +
            "\n" +
            "no-reply@white753.onmicrosoft.com\n" +
            "\n" +
            "no_reply@kadfa.beebom.online\n" +
            "\n" +
            "noreply-accountreport7981-4217@kgfyhy.cuanapple.com\n" +
            "\n" +
            "noreply.bidadariberkhontolbergijiltelu-27uj7iakg@27uj7iakg.xayeuyamazon.com\n" +
            "\n" +
            "noreply@aaa.membershipmail.net\n" +
            "\n" +
            "noreply@capitalonesettlement.com\n" +
            "\n" +
            "noreply@carlmichael25.onmicrosoft.com\n" +
            "\n" +
            "noreply@classcreator.net\n" +
            "\n" +
            "noreply@clicktactix.com\n" +
            "\n" +
            "noreply@designeroutletsoltau.com\n" +
            "\n" +
            "noreply@hostpapa.com\n" +
            "\n" +
            "noreply@id.yandex.com.tr\n" +
            "\n" +
            "noreply@livellocasa.it\n" +
            "\n" +
            "noreply@mail.saylor.org\n" +
            "\n" +
            "noreply@olyautobody.com\n" +
            "\n" +
            "noreply@pancakeswap.finance\n" +
            "\n" +
            "noreply@parkrun.com\n" +
            "\n" +
            "noreply@runsignup.com\n" +
            "\n" +
            "noreply@schneiderfuneraldirectors.com\n" +
            "\n" +
            "noreply@secure-mailer.info\n" +
            "\n" +
            "noreply@sonobello.com\n" +
            "\n" +
            "noreply@woolrich.com\n" +
            "\n" +
            "norwegiancruiseline@email.ncl.com\n" +
            "\n" +
            "ntl5nly3sdm2xn0hrbejifugnnkaaxp5cd6iwgizkeb6xr-46bcq98k0hyjiou1nt@att-agentmail.com\n" +
            "\n" +
            "nv03sl.outreach@mail.house.gov\n" +
            "\n" +
            "odgjznqpbcevqdostluhyvsuwrk@healthaza.org\n" +
            "\n" +
            "ofbcdjnmao@tyofv.rmsm.swartzbois.com\n" +
            "\n" +
            "offers@t.e-thingsremembered.com\n" +
            "\n" +
            "offers@w.e-thingsremembered.com\n" +
            "\n" +
            "officedepot@express.medallia.com\n" +
            "\n" +
            "offleash@tryfi.com\n" +
            "\n" +
            "ollies@armyemail.ollies.us\n" +
            "\n" +
            "oneplace@cheapviagrastore.com\n" +
            "\n" +
            "order-update@parcor77.jedimasters.net\n" +
            "\n" +
            "orders@alchemyfinehome.com\n" +
            "\n" +
            "orders@behrens281.onmicrosoft.com\n" +
            "\n" +
            "orders@iloverebbq.com\n" +
            "\n" +
            "ordersorwmx7hc1am1@orwmx7hc1am1traderecruitment.co.nz\n" +
            "\n" +
            "orgzjkr@email.hwzkmkt.org\n" +
            "\n" +
            "oudtgom@email.bzpwahr.org\n" +
            "\n" +
            "p04bxqvbklywisj-jvyvqikw0dx4jso0-9qokjx8w-13351161@mail.com\n" +
            "\n" +
            "partners@quadpay.com\n" +
            "\n" +
            "pbinfo@musl.com\n" +
            "\n" +
            "peak@voluptatibusgbbjh.kertbandsok.info\n" +
            "\n" +
            "pggmmzq@email.whspjiu.org\n" +
            "\n" +
            "phtlnw4csd@09v5.molimen.co.uk\n" +
            "\n" +
            "postit@arsgzp.jaktan.info\n" +
            "\n" +
            "postit@atquexvpil.unicef-asia.com\n" +
            "\n" +
            "postit@beataepovps.persoluxure.com\n" +
            "\n" +
            "postit@consequaturozulp.resumain.shop\n" +
            "\n" +
            "postit@contact-us.in\n" +
            "\n" +
            "postit@corporisogflt.pfizerinc.org\n" +
            "\n" +
            "postit@cupiditateuzipe.aragoza.blog\n" +
            "\n" +
            "postit@dewmme.contact-us.in\n" +
            "\n" +
            "postit@doloremckqiq.bullbassor.me\n" +
            "\n" +
            "postit@dolorumgurpe.kismint.net\n" +
            "\n" +
            "postit@eligendiamhai.kismint.net\n" +
            "\n" +
            "postit@estbwhau.tofreeprivacy.com\n" +
            "\n" +
            "postit@ipsumavrkk.persoluxure.com\n" +
            "\n" +
            "postit@jaktan.info\n" +
            "\n" +
            "postit@kismint.net\n" +
            "\n" +
            "postit@maximettigz.hugevariety.cc\n" +
            "\n" +
            "postit@minusvxehu.hugevariety.cc\n" +
            "\n" +
            "postit@nisivkpbd.kismint.net\n" +
            "\n" +
            "postit@pgljgz.jaktan.info\n" +
            "\n" +
            "postit@quibrvbe.privacyguardhelp.com\n" +
            "\n" +
            "postit@quidemiuguw.privacyguardhelp.com\n" +
            "\n" +
            "postit@reiciendisxpvdo.tofreeprivacy.com\n" +
            "\n" +
            "postit@resumain.shop\n" +
            "\n" +
            "postit@saepeylhfz.smartdrops.me\n" +
            "\n" +
            "postit@sintxintr.smartdrops.me\n" +
            "\n" +
            "postit@suscipitjhfrh.resumain.shop\n" +
            "\n" +
            "postit@tofreeprivacy.com\n" +
            "\n" +
            "postit@unicef-asia.com\n" +
            "\n" +
            "postit@uthjpsw.calemero.club\n" +
            "\n" +
            "postit@utnkvza.hugevariety.cc\n" +
            "\n" +
            "postit@vijoea.jaktan.info\n" +
            "\n" +
            "postit@voluptasgedsb.persoluxure.com\n" +
            "\n" +
            "postit@vvrpyn.contact-us.in\n" +
            "\n" +
            "postmaster@mychway.com\n" +
            "\n" +
            "pr@tjskids.com\n" +
            "\n" +
            "prachisharmaseo@outlook.com\n" +
            "\n" +
            "praise_legrande484x782@hotmail.com\n" +
            "\n" +
            "product-updates@boodpecker.co\n" +
            "\n" +
            "production@clothes2order.com\n" +
            "\n" +
            "promo@sabrinasiegl934.onmicrosoft.com\n" +
            "\n" +
            "promos@zagg.com\n" +
            "\n" +
            "puritanspride@e.puritan.com\n" +
            "\n" +
            "qftpxgnmceyukxq-rcfxz-yarvxxilhztwjif@bateriesh.com\n" +
            "\n" +
            "qgmc@email.czaa.org\n" +
            "\n" +
            "quynhanh10072012@gmail.com\n" +
            "\n" +
            "qvc@nkrv.onmicrosoft.com\n" +
            "\n" +
            "qvprjb.xuplrwi@hvbrxvmwst.perrychristinejacobs.work\n" +
            "\n" +
            "raolson@staylocalsavebig.biz\n" +
            "\n" +
            "raquel@temporadalivre.com\n" +
            "\n" +
            "registrar@negrelli9c.onmicrosoft.com\n" +
            "\n" +
            "reply@email.harmandio.com\n" +
            "\n" +
            "rewards@bjerggrethe.onmicrosoft.com\n" +
            "\n" +
            "rhybgkk@email.avkgulw.org\n" +
            "\n" +
            "rqruzuh@email.gnzjhsw.org\n" +
            "\n" +
            "rwavgf7oxfn3y5l-wzcoelv0hhvchzvn@googlegroups.com\n" +
            "\n" +
            "ryan@lovejoywellness.biz\n" +
            "\n" +
            "ryan@lovejoywellness.net\n" +
            "\n" +
            "saksfifthavenue@news.saks.com\n" +
            "\n" +
            "salem@vampfangs.com\n" +
            "\n" +
            "sales@grosssu6.onmicrosoft.com\n" +
            "\n" +
            "sales@nadinegrab55.onmicrosoft.com\n" +
            "\n" +
            "sales@silverprint.co.uk\n" +
            "\n" +
            "sales@theprintcompany.co.za\n" +
            "\n" +
            "sales@wilkinson.co.uk\n" +
            "\n" +
            "scott@yunnansourcing.com\n" +
            "\n" +
            "seawolves@seawolves.com\n" +
            "\n" +
            "selezione@oggilavoro.eu\n" +
            "\n" +
            "send@crownawardsmarketing.com\n" +
            "\n" +
            "sender@maverickcrm.com\n" +
            "\n" +
            "service@hairfreesales.com\n" +
            "\n" +
            "shannon@email.starexpanses.com\n" +
            "\n" +
            "shop@men24x7.com\n" +
            "\n" +
            "shop@salsalzb.onmicrosoft.com\n" +
            "\n" +
            "shows@d2p.com\n" +
            "\n" +
            "sjhqvyz@email.mizetrd.org\n" +
            "\n" +
            "song@of-the-day.com\n" +
            "\n" +
            "store-news@dealsofyou.com\n" +
            "\n" +
            "store-news@filmyglobal.com\n" +
            "\n" +
            "store-news@painale.com\n" +
            "\n" +
            "store-news@worldbestbuys.com\n" +
            "\n" +
            "store88t9gp@88t9gpoldearth.calderdale.sch.uk\n" +
            "\n" +
            "storeafdgnr@afdgnrmgsh.net\n" +
            "\n" +
            "storeatgouz@atgouzhaloasisminnesota.com\n" +
            "\n" +
            "storebyrkhq@byrkhqjsms.pe\n" +
            "\n" +
            "storeejnwgv@ejnwgvlezzi.info\n" +
            "\n" +
            "storeensmkj@ensmkjstabcps.uk\n" +
            "\n" +
            "storekv7kid@kv7kidtripleselpaso.com\n" +
            "\n" +
            "stores@0qztvahanoverautomotive.co.nz\n" +
            "\n" +
            "stores@oqnqw4hikari.co.nz\n" +
            "\n" +
            "style@badcock.email\n" +
            "\n" +
            "subscription.service@dubscriptions.dsa.gov\n" +
            "\n" +
            "subscriptions@medium.com\n" +
            "\n" +
            "support@bichler454.onmicrosoft.com\n" +
            "\n" +
            "support@blissy.com\n" +
            "\n" +
            "support@businessteam.iabmr.sensekey.biz\n" +
            "\n" +
            "support@grssgst96.onmicrosoft.com\n" +
            "\n" +
            "support@kampst6.onmicrosoft.com\n" +
            "\n" +
            "support@metamask.shoes\n" +
            "\n" +
            "support@stickergiant.com\n" +
            "\n" +
            "support@wiggle.co.uk\n" +
            "\n" +
            "supporthqvu@hqvuaxconnect.com\n" +
            "\n" +
            "supportogka@ogkaaxconnect.com\n" +
            "\n" +
            "surveys@marlenraun.onmicrosoft.com\n" +
            "\n" +
            "sven@rapidmail.com\n" +
            "\n" +
            "sylviamccoskey1999@hotmail.com\n" +
            "\n" +
            "talktoace@express.medallia.com\n" +
            "\n" +
            "tanvihegde1@outlook.com\n" +
            "\n" +
            "team09@elsecore.info\n" +
            "\n" +
            "teethkits@homeinsiderz.com\n" +
            "\n" +
            "tima772017@gmail.com\n" +
            "\n" +
            "tlglexingtoneastky@thelittlegym.com\n" +
            "\n" +
            "traian.iliescu@phys.ubbcluj.ro\n" +
            "\n" +
            "tvpzykfrivgduntomqwgozmsjwf@infory.org\n" +
            "\n" +
            "tvuffvvoqhmicsfm8ggifk8ev@messaggi.immobiliare.it\n" +
            "\n" +
            "twqhdkc@email.knmepeb.org\n" +
            "\n" +
            "tylertool@emails.tylertool.com\n" +
            "\n" +
            "umjxobh@email.ohplsmy.org\n" +
            "\n" +
            "underarmour@emails.underarmour.com\n" +
            "\n" +
            "updates@internationalmedicalcorps.org\n" +
            "\n" +
            "uwjcfep@email.jznjmyr.org\n" +
            "\n" +
            "uypuos9fzi@nhlrr.5hsx.yabby.co.uk\n" +
            "\n" +
            "val@engagebay.co\n" +
            "\n" +
            "verify@databeamcenter.com\n" +
            "\n" +
            "visitscotland@emails.visitscotland.com\n" +
            "\n" +
            "vlxou5mlac@wmyi.swartzbois.com\n" +
            "\n" +
            "volunteer@marckapeller35.onmicrosoft.com\n" +
            "\n" +
            "volunteer@nhsresponders.co.uk\n" +
            "\n" +
            "webms@email.gsua.org\n" +
            "\n" +
            "webms@email.memw.org\n" +
            "\n" +
            "webms@email.qjzp.org\n" +
            "\n" +
            "webms@email.rgcf.org\n" +
            "\n" +
            "webms@email.zpfh.org\n" +
            "\n" +
            "webshop@augustindom55.onmicrosoft.com\n" +
            "\n" +
            "websiteservice@outlook.com\n" +
            "\n" +
            "wecare@soderbergsflorist.com\n" +
            "\n" +
            "williamssonoma@kevinokab25.onmicrosoft.com\n" +
            "\n" +
            "windscribe785accet96braind310donhij@speedsearch2u.co.uk\n" +
            "\n" +
            "wlkt@email.iheart.com\n" +
            "\n" +
            "wpsoffices@maxwar.info\n" +
            "\n" +
            "xbhfqrafzwkonmb-zyrqd-zdjvbsmgfkpwevx@conectarais.org\n" +
            "\n" +
            "xhumroc@email.cvzsuag.org\n" +
            "\n" +
            "xojwafl@email.sfgmxfs.org\n" +
            "\n" +
            "xrbxptb@email.rczlurv.org\n" +
            "\n" +
            "xvgjmwc@email.hxbnath.org\n" +
            "\n" +
            "yarnspirations@email.yarnspirations.com\n" +
            "\n" +
            "your.friends@news.bankrate.com\n" +
            "\n" +
            "ypjffrmyby7nr7p-sikzt29fnoqlbbps@googlegroups.com\n" +
            "\n" +
            "ysamovr@email.xfdcwkv.org\n" +
            "\n" +
            "yvplzcx@email.ofgtxjp.org\n" +
            "\n" +
            "yzhjsor@email.wpyagtm.org\n" +
            "\n" +
            "zales@em.zales.com\n" +
            "\n" +
            "zbanuyv@email.tkkkmtv.org\n" +
            "\n" +
            "zennioptical@mail.zennioptical.com\n" +
            "\n" +
            "zhrntre@email.qxbxovi.org\n" +
            "\n" +
            "zina@eoosend.com\n" +
            "zznews@newsletter.zzounds.com").split("\n\n");

    public List<String> unblockable = new ArrayList<>();



}
