import java.util.*;

public class Main {
    public static void main(String[] args) {

        List<String> ignoreList = new ArrayList<>(Arrays.asList(nonblockable));

        Map<String, Integer> repeatingDomains = new HashMap();


        for (int i = 0; i < mails.length; i++) {
            mails[i] = mails[i].split("@")[1];
            String domain = mails[i];

            if (repeatingDomains.containsKey(domain)) {
                int count = repeatingDomains.get(domain);
                repeatingDomains.replace(domain, ++count);
                if (count >= 3 && !ignoreList.contains(domain)) {
                    System.out.println(domain + " " + count);
                }
            } else {
                repeatingDomains.put(domain, 1);
            }
        }
    }

    static String[] nonblockable = {
            "gmail.com", "googlegroups.com", "hotmail.com", "outlook.com"};

    static String[] mails = ("a@covaani.com\n" +
            "\n" +
            "a@troopicall.com\n" +
            "\n" +
            "adv@eyc2wmw7z7fe.gradoit.it\n" +
            "\n" +
            "affiliate-profits@1wqg9txtj.i-associate.com\n" +
            "\n" +
            "aj@tuymdwjrr.aj-com.net\n" +
            "\n" +
            "arianna@vdtjbqnag.a-piu-srl.com\n" +
            "\n" +
            "artsci.communications@pgkhczeey.usask.ca\n" +
            "\n" +
            "claudia@6vz1ni4oc.ceetiz.com\n" +
            "\n" +
            "contact@frenchshaken.click\n" +
            "\n" +
            "contact@incomestatementjournal.com\n" +
            "\n" +
            "contact@laqrxtrdg.simonemahler.net\n" +
            "\n" +
            "contact@linandelle.com\n" +
            "\n" +
            "contact@marinasmirlo.co.uk\n" +
            "\n" +
            "contact@oki8wdxpe.tedxparis.com\n" +
            "\n" +
            "contact@patriotmomdigest.com\n" +
            "\n" +
            "contact@qgoegl.brailleskateboarding.com\n" +
            "\n" +
            "contact@quomweok.pfizerinc.me\n" +
            "\n" +
            "contact@speedmarket.live\n" +
            "\n" +
            "contact@teachtable.click\n" +
            "\n" +
            "contact@tomorrowevening.click\n" +
            "\n" +
            "contact@voluptatemltfid.ezabelpy.org.uk\n" +
            "\n" +
            "contact@xaclmqmp3.flawlesslashesbyloreta.fr\n" +
            "\n" +
            "contacto@emilyschwab14.onmicrosoft.com\n" +
            "\n" +
            "contacto@pxz9dbeh8.compradelsur.es\n" +
            "\n" +
            "contato@lut.com.br\n" +
            "\n" +
            "contato@zfelvii3sx8.novidades.hurb.com\n" +
            "\n" +
            "cs.9s6zbjlhrg9xndxx8xx94dme5kmo8wtgznk-yjou3t8waqja7igfk@emaildl.att-mail.com\n" +
            "\n" +
            "cs.av9cgkaxj3arcmqi4ddhdv2dvxxcvzxbt20-lea3lxpgskgiufaqs@emaildl.att-mail.com\n" +
            "\n" +
            "cs@email.quhh.org\n" +
            "\n" +
            "cs@email.rpep.org\n" +
            "\n" +
            "cs@email.vxer.org\n" +
            "\n" +
            "cs@email.zway.org\n" +
            "\n" +
            "cs@rlwrmqowsdfia.kochiy.me\n" +
            "\n" +
            "csz4lpxqtiodwux-olihsrpdkvpejgro@firefoxgroups.com\n" +
            "\n" +
            "currentcatalog@aufeld9a.onmicrosoft.com\n" +
            "\n" +
            "customer.services@bw3kf57ix.loot.com\n" +
            "\n" +
            "customer.support@clothes2order.com\n" +
            "\n" +
            "customer_support@email.ticketmaster.com\n" +
            "\n" +
            "customercare@email.vioc.com\n" +
            "\n" +
            "customerservice0gvd@thymepeoria.com\n" +
            "\n" +
            "customerservice51sn7ehnfnpz@51sn7ehnfnpzconstructionreporter.com\n" +
            "\n" +
            "customerservice596324818754@596324818754squarespace.com\n" +
            "\n" +
            "customerservice5otisr63bjjz@5otisr63bjjzthesiliconreview.com\n" +
            "\n" +
            "customerservice6ut1pdvwmw7v@6ut1pdvwmw7vcapselectric.cl\n" +
            "\n" +
            "customerservice@abcstores.com\n" +
            "\n" +
            "customerservice@ameswalker.com\n" +
            "\n" +
            "customerservice@ix5qwbk9v.ahrf.com\n" +
            "\n" +
            "customerservice@mbeans.com\n" +
            "\n" +
            "customerservice@simplesite.com\n" +
            "\n" +
            "customerservice@tfsnyc.com\n" +
            "\n" +
            "customerservice@ticwatches.co.uk\n" +
            "\n" +
            "customerservice@yarn.com\n" +
            "\n" +
            "customerservicebrdfpmzgst3t@sochware.com\n" +
            "\n" +
            "customerservicedxdn3idtvezw@noon.partners\n" +
            "\n" +
            "customerservicedxsqay0ieuxt@dxsqay0ieuxtcanastennis.com\n" +
            "\n" +
            "customerservicedydkuekd8txw@dydkuekd8txwfawnmontanye.com\n" +
            "\n" +
            "customerserviceee3vlt8zhjyn@laser-mayhem.com\n" +
            "\n" +
            "customerserviceesuagjqoortn@laser-mayhem.com\n" +
            "\n" +
            "customerserviceevgkfzhzstiuw@vxnugreensealsafety.com\n" +
            "\n" +
            "customerservicehvfidsg9jeav@h-is4.com\n" +
            "\n" +
            "customerservicej6psgywkbaiv@investing.com\n" +
            "\n" +
            "customerservicejfqxzmfajsrl@jfqxzmfajsrldeltatax.se\n" +
            "\n" +
            "customerservicejz27l0na3g6q@noon.partners\n" +
            "\n" +
            "customerservicek0zvdxf2l24p@k0zvdxf2l24pthekeeledeal.com\n" +
            "\n" +
            "customerservicemzjh@mzjhwparrishlaw.com\n" +
            "\n" +
            "customerservicenorgmrg6uu36@norgmrg6uu36stakspancakes.com\n" +
            "\n" +
            "customerservicep4y6rqz7dhl1@p4y6rqz7dhl1jbassdrop.com\n" +
            "\n" +
            "customerservicerjwe@rjwevincentetdussault.com\n" +
            "\n" +
            "customerservicerngo@rngodevroedtenthierry.com\n" +
            "\n" +
            "customerservices@zwvmlx0pi.portmeiriongroup.com\n" +
            "\n" +
            "customerservicesdnc@sdnclcsmd.org\n" +
            "\n" +
            "customerserviceu8czxurdn2yb@u8czxurdn2ybthesiliconreview.com\n" +
            "\n" +
            "customerserviceuadf63a5m8cr@uadf63a5m8crmmhconsulting.net\n" +
            "\n" +
            "customerservicew1x2dbcjahmn@w1x2dbcjahmnwsimg.com\n" +
            "\n" +
            "customerservicewcab@wcaballtechcomm.net\n" +
            "\n" +
            "customerservicexggm1gv1gvex@acclaimshop.com.au\n" +
            "\n" +
            "customerservicexgipvhjibpsa@xgipvhjibpsagroomfield.co.uk\n" +
            "\n" +
            "customerservicezla8n1m0aoym@laser-mayhem.com\n" +
            "\n" +
            "customersupport@02840.royalelastics.com\n" +
            "\n" +
            "czpjbzd@email.yxkqstp.org\n" +
            "\n" +
            "daily@etbizb.please.getluckyticket.com\n" +
            "\n" +
            "daivik@seosmoppc.net\n" +
            "\n" +
            "dallas@well.com\n" +
            "\n" +
            "dalnyywr3b7qszg-52rgorlawn1tbccl@googlegroups.com\n" +
            "\n" +
            "dannyd@cleanitsupply.com\n" +
            "\n" +
            "das3etaypacddigooepd-ynnqxdpmv663@hatchiokay.eu\n" +
            "\n" +
            "data-delivery-id205943781@mail.klicksend.com.br\n" +
            "\n" +
            "deals@9rbcbgbitdv.e.cruisemegastore.com.au\n" +
            "\n" +
            "depelu.management@gmail.com\n" +
            "\n" +
            "designstudio@8dapudzpw.inspirationinteriors.com\n" +
            "\n" +
            "dev@hzljempw.arkency.com\n" +
            "\n" +
            "development@nxpgabla.arenapharm.com\n" +
            "\n" +
            "dish@maioresjmekl.joebiden2020.me\n" +
            "\n" +
            "dish@remztwhl.ourfriends.me\n" +
            "\n" +
            "disk@mail.yandex.ru\n" +
            "\n" +
            "diving@6xdgh6smv.aliveaboard.com\n" +
            "\n" +
            "doe@prasarana.com.my\n" +
            "\n" +
            "donotreply@sbni3yqx.em.lordandtaylor.com\n" +
            "\n" +
            "douglas54jzxyzwlwe7vgq6upged8owz78az3@vybo4pxiqlwk.com\n" +
            "\n" +
            "dsg@e.dcsg.com\n" +
            "\n" +
            "durex@e.durex.com\n" +
            "\n" +
            "e-news@v7gcnmj.santaslapland.com\n" +
            "\n" +
            "edieuropa@vbmhcp33n.tiscali.it\n" +
            "\n" +
            "editorial@liveandinvestoverseas.com\n" +
            "\n" +
            "ekdesmirfvxcotk-ukwju-bjrbzlqsfhnzwrc@3xmispatch.org\n" +
            "\n" +
            "elhub@vhrtbs.linnbenton.edu\n" +
            "\n" +
            "elizabeth@email.flounderspecial.com\n" +
            "\n" +
            "elm@email.cbvizuo.org\n" +
            "\n" +
            "elm@email.fhbvlqc.org\n" +
            "\n" +
            "elm@email.jgdeslk.org\n" +
            "\n" +
            "elm@email.jjvtmhk.org\n" +
            "\n" +
            "elm@email.jnbnneo.org\n" +
            "\n" +
            "elm@email.nygjlsu.org\n" +
            "\n" +
            "elm@email.vhapkds.org\n" +
            "\n" +
            "elm@email.yymxj.org\n" +
            "\n" +
            "elm@email.zreaxfp.org\n" +
            "\n" +
            "email-noreply@hvmyta.email1.ecoatm.com\n" +
            "\n" +
            "email@burtscher040.onmicrosoft.com\n" +
            "\n" +
            "email@e.krogermail.com\n" +
            "\n" +
            "email@osttzb.email.emailaflac-email.com\n" +
            "\n" +
            "email@service.marksandspencer.com\n" +
            "\n" +
            "email@uhnsd.emails.jawbone.com\n" +
            "\n" +
            "email@winnrich.onmicrosoft.com\n" +
            "\n" +
            "emailaftrbfo@zm3dk.onmicrosoft.com\n" +
            "\n" +
            "emailhjckyuw@4mqxwd.onmicrosoft.com\n" +
            "\n" +
            "emailqpmdjwv@6rjb5r.onmicrosoft.com\n" +
            "\n" +
            "emails@9dqnhxri64.diamondtour.com\n" +
            "\n" +
            "emails@uritishmuseum.org\n" +
            "\n" +
            "emailznvdadx@4vdqls.onmicrosoft.com\n" +
            "\n" +
            "emarketing@cqqwm.gilman-group.com\n" +
            "\n" +
            "emarketing@e.netgear.com\n" +
            "\n" +
            "emedia@hkqvdug8u.artreview.com\n" +
            "\n" +
            "enews@iukkby.komatsu.com.au\n" +
            "\n" +
            "eservice@harlandclarke.com\n" +
            "\n" +
            "estatements@sccu.com\n" +
            "\n" +
            "euna86liiuogycp-qemm7s2gxxdp4swn@googlegroups.com\n" +
            "\n" +
            "evelyn@jollyredz.com\n" +
            "\n" +
            "events@jz68lqld.communications.onekingslane.com\n" +
            "\n" +
            "factorydirectcraft@factorydirectcraft.com\n" +
            "\n" +
            "fairpriceonline@fpdzsg.online.fairprice.com.sg\n" +
            "\n" +
            "familiaserra@11086.lamejornaranja.com\n" +
            "\n" +
            "familiaserra@27060.lamejornaranja.com\n" +
            "\n" +
            "fastdatingsupport@livehelpnow.net\n" +
            "\n" +
            "films@tp5gair7qqkybwxxjv.americanexperience.wgbh.org\n" +
            "\n" +
            "fjakvxjdjj@9v7f.greathearted.live\n" +
            "\n" +
            "flavioaugusto@2ta2fixhp.wiseup.com\n" +
            "\n" +
            "flickrteam@arrow.flickr.com\n" +
            "\n" +
            "francesc@ryidjk.corredormato.com\n" +
            "\n" +
            "friends@date.com\n" +
            "\n" +
            "friends@email.christmascentral.com\n" +
            "\n" +
            "funships@carnivalcruiselineemail.com\n" +
            "\n" +
            "gaia@goto.gaia.com\n" +
            "\n" +
            "galls@salzbu6.onmicrosoft.com\n" +
            "\n" +
            "geappliances@hqcncs.info.geappliances.com\n" +
            "\n" +
            "gemma@8lcoqaw7w.gemmaford.com\n" +
            "\n" +
            "gfile@ha.com\n" +
            "\n" +
            "gianna@vanillaspicelife.com\n" +
            "\n" +
            "glvzlrk@email.ixceadw.org\n" +
            "\n" +
            "goaheadtours@fzpkriry.email.goaheadtours.com\n" +
            "\n" +
            "gollo@xbe0hv4eykal.unicomermktg.com\n" +
            "\n" +
            "gorazd.skrt@lsv26idhx.lovely-trips.com\n" +
            "\n" +
            "grandpalais@na9ri1bk2.email.newsrmngrandpalais.fr\n" +
            "\n" +
            "gustavoschwanka@ufpr.br\n" +
            "\n" +
            "guyparfitt@yp4pbib.williamdartmouth.org.uk\n" +
            "\n" +
            "gwpkxbcouerbasciftjvzngwdvh@healthbia.co.uk\n" +
            "\n" +
            "hanna.dabrowska@mkzrire.linkflora-mail.com\n" +
            "\n" +
            "haydene.dunn@kznhealth.gov.za\n" +
            "\n" +
            "headlines@l8tpw4xos4c.mb.healthiertalk.com\n" +
            "\n" +
            "helenvriniotis@processcomanagement.com\n" +
            "\n" +
            "heliabrine@vw897begx.asepta.mc\n" +
            "\n" +
            "hello70464@70464glowskinco.co\n" +
            "\n" +
            "hello@eo2w5z84h.onepoundeliquid.com\n" +
            "\n" +
            "hello@k8etcuul4.addmotor.com\n" +
            "\n" +
            "hello@n4sv7w.rosefieldwatches.com\n" +
            "\n" +
            "hello@peajhtyh.email.thecolvinco.com\n" +
            "\n" +
            "hello@rwbfzfok6ds2.shepherds.com.au\n" +
            "\n" +
            "hello@sundaycitizen.me\n" +
            "\n" +
            "hello@tortugabackpacks.com\n" +
            "\n" +
            "help+newsletter@eigenendf.onmicrosoft.com\n" +
            "\n" +
            "help@4o4edanrbo.ingnapoli.com\n" +
            "\n" +
            "help@yutopilotapp.com\n" +
            "\n" +
            "helzberg@uhcb94.emails.helzberg.com\n" +
            "\n" +
            "hola@a2cylxjef.my.zalando-prive.es\n" +
            "\n" +
            "hollister@kerstinziegler584.onmicrosoft.com\n" +
            "\n" +
            "home@icgieyevdpj.e-mail.technogym.com\n" +
            "\n" +
            "houseparty@v2rwkakcbv1.houseparty.com\n" +
            "\n" +
            "i7ls0npkyqltcfa-n5rejypuqlykt57i@opzy54bg-63180549.net\n" +
            "\n" +
            "icdtasaemarketing@imf.org\n" +
            "\n" +
            "igfmobb@email.cmljjav.org\n" +
            "\n" +
            "ines@tcjwtrsp.latrastienda.com.uy\n" +
            "\n" +
            "info.audi@okdrpgnj6.grafhardenberg.de\n" +
            "\n" +
            "info.operationrescue@gmail.com\n" +
            "\n" +
            "info038451@038451bectorfoods.com\n" +
            "\n" +
            "info506464294@mailva.evite.com\n" +
            "\n" +
            "info@19121.capstoneprep.com\n" +
            "\n" +
            "info@1cjilvsvf.m.missouriquiltco.com\n" +
            "\n" +
            "info@1mvoseg.indestructibleme.com\n" +
            "\n" +
            "info@247998.cleverpatch.com.au\n" +
            "\n" +
            "info@382776.pandomo.nl\n" +
            "\n" +
            "info@49024.ssp-online.nl\n" +
            "\n" +
            "info@49028.global-petro.com\n" +
            "\n" +
            "info@4mre5sda5e.alf-hb.de\n" +
            "\n" +
            "info@4wi1e8bctmfu.allinpackaging.com\n" +
            "\n" +
            "info@5iamyfmbbtef.artesanosdesign.com\n" +
            "\n" +
            "info@7dtibdd.pacoperfumerias.com\n" +
            "\n" +
            "info@8gyofyvpd.southeritage.it\n" +
            "\n" +
            "info@924024.theperfumersstory.com\n" +
            "\n" +
            "info@apdylk.steunkousen.nl\n" +
            "\n" +
            "info@aughod1ir.martial-art-concepts.co.uk\n" +
            "\n" +
            "info@bbi-reizen.nl\n" +
            "\n" +
            "info@bc.adorama.com\n" +
            "\n" +
            "info@blueforcefleet.com\n" +
            "\n" +
            "info@campingnavigator.com\n" +
            "\n" +
            "info@cjheh.updates.golf.nl\n" +
            "\n" +
            "info@coolshoes.com\n" +
            "\n" +
            "info@democraticvoters.org\n" +
            "\n" +
            "info@djhrlnn06.screenline.it\n" +
            "\n" +
            "info@dks6gmy0blv.homecenter.nl\n" +
            "\n" +
            "info@doqc.petclic.com\n" +
            "\n" +
            "info@dpwgir.broadwayinstanley.com\n" +
            "\n" +
            "info@dtsqldvtcdst.angusbarrett.com.au\n" +
            "\n" +
            "info@e6fwrufky.sguardocontemporaneo.it\n" +
            "\n" +
            "info@elviajerofisgon.com\n" +
            "\n" +
            "info@email.sygic.com\n" +
            "\n" +
            "info@epbqtocb.proaudiostar.com\n" +
            "\n" +
            "info@etntxth.preshopeit.info\n" +
            "\n" +
            "info@eywaym61mq8i.sublime.nl\n" +
            "\n" +
            "info@ezatyt6jbb.g4bygolpa.com\n" +
            "\n" +
            "info@f7jqz76kuwer.projectgezond.nl\n" +
            "\n" +
            "info@fbkcuxgibak.bazardelvapeo.com\n" +
            "\n" +
            "info@fyb8ntwmv7g0.modern-storyteller.com\n" +
            "\n" +
            "info@granddezign.com\n" +
            "\n" +
            "info@hcipy.omjcfc.org\n" +
            "\n" +
            "info@helmutritter63.onmicrosoft.com\n" +
            "\n" +
            "info@iceshaker.com\n" +
            "\n" +
            "info@ipjlgxslf.fit2flypcr.co.uk\n" +
            "\n" +
            "info@janineschachner.onmicrosoft.com\n" +
            "\n" +
            "info@justlikeoldtimes.net\n" +
            "\n" +
            "info@kdnaaol.langimmobilien.de\n" +
            "\n" +
            "info@ls3qwlozp037.ciboapp.com\n" +
            "\n" +
            "info@lwnqnmoti.mm-turist.net\n" +
            "\n" +
            "info@mail.vetsource.com\n" +
            "\n" +
            "info@mapmyfitness-t.messages4.com\n" +
            "\n" +
            "info@mdv.zooninverse.online\n" +
            "\n" +
            "info@mtpgvp.lafarmaciaonline.es\n" +
            "\n" +
            "info@mvkgvbbg.puuree.com\n" +
            "\n" +
            "info@myiclubonline.com\n" +
            "\n" +
            "info@n.zavvi.com\n" +
            "\n" +
            "info@news.tactics.com\n" +
            "\n" +
            "info@nq3qpqea1htf.lemoni.gr\n" +
            "\n" +
            "info@nqqgq3asr.paintpeople.co.uk\n" +
            "\n" +
            "info@nqzxcc.promperu-turismoin.pe\n" +
            "\n" +
            "info@ntlqqq.hausen-gottschalk.de\n" +
            "\n" +
            "info@ojsxwt.sawmilladventurepark.com\n" +
            "\n" +
            "info@ozkqjfyux.lovatoelectric.com\n" +
            "\n" +
            "info@panu.dreamscoops.online\n" +
            "\n" +
            "info@peepconsulting.com\n" +
            "\n" +
            "info@pg2e.rwpark.com\n" +
            "\n" +
            "info@pgsqlvum.newsletter.pilotflyingj.com\n" +
            "\n" +
            "info@pmkmyz.1styles.pro\n" +
            "\n" +
            "info@pplgynd5z.caledoniancampers.co.uk\n" +
            "\n" +
            "info@qputasv.gotcourts.com\n" +
            "\n" +
            "info@qrye2y0wt.mozaiektegeltjes-enzo.nl\n" +
            "\n" +
            "info@qxfdxer54aff.play-inutrecht.nl\n" +
            "\n" +
            "info@qyxl3ss7.updates.indeedorb.com\n" +
            "\n" +
            "info@rdcp4c.mailpa.mdrctr.com\n" +
            "\n" +
            "info@rerumazvbx.joebiden2020.me\n" +
            "\n" +
            "info@revistaaqua.com\n" +
            "\n" +
            "info@riecastdepotshop.com\n" +
            "\n" +
            "info@rzoephusuwis.birdie-open.com\n" +
            "\n" +
            "info@selecthomewarranty.com\n" +
            "\n" +
            "info@sheabelpets.com\n" +
            "\n" +
            "info@signupgenius.com\n" +
            "\n" +
            "info@sse4oj0ny.yourparkingspace.co.uk\n" +
            "\n" +
            "info@staysure.co.uk\n" +
            "\n" +
            "info@steveweissmusic.com\n" +
            "\n" +
            "info@stringsandbeyond.com\n" +
            "\n" +
            "info@taxhelpoffer.com\n" +
            "\n" +
            "info@tazdvj.misdiablillos.com\n" +
            "\n" +
            "info@tennis-warehouse.com\n" +
            "\n" +
            "info@thewreathshop.com\n" +
            "\n" +
            "info@tulumba.com\n" +
            "\n" +
            "info@ubk2cuw7l.mail.which.co.uk\n" +
            "\n" +
            "info@uc8kgkcgw.radiancecleanse.com\n" +
            "\n" +
            "info@unipak.com.tr\n" +
            "\n" +
            "info@uqmzwrq0v.collectivedesignfair.com\n" +
            "\n" +
            "info@uwcqvk6pw.melaseccapressoffice.it\n" +
            "\n" +
            "info@vlopaoit6ezmoptimusu.com\n" +
            "\n" +
            "info@vonkp.hievej.unionjackgolf.com\n" +
            "\n" +
            "info@vovacft3rfwz.popontop.nl\n" +
            "\n" +
            "info@vsg.wealthplus.online\n" +
            "\n" +
            "info@vsvz5wzin.dewits.co.za\n" +
            "\n" +
            "info@wandp.com\n" +
            "\n" +
            "info@wf5sw2iwkyw.occyachting.com\n" +
            "\n" +
            "info@willie.nl\n" +
            "\n" +
            "info@wknub7xlajwn.gutsgusto.com\n" +
            "\n" +
            "info@wouahfdr.m.kaineroshop.com\n" +
            "\n" +
            "info@xi6z1nw.gesundheitsmanufaktur.de\n" +
            "\n" +
            "info@xnhjfd.dermaquestinc.co.uk\n" +
            "\n" +
            "info@ykqlvaiwmr.keeledscales.com\n" +
            "\n" +
            "info@ywijud.contactevents.london\n" +
            "\n" +
            "info@zcbr3xgwc.modedesigncollege.de\n" +
            "\n" +
            "info@zerkxnjf.fietshelm3.com\n" +
            "\n" +
            "info@zuscg0w05.santamonicaproductions.com\n" +
            "\n" +
            "infoiighki@iighkiveritaspress.com\n" +
            "\n" +
            "infopboljwkhb5uo@grupocpc.ar\n" +
            "\n" +
            "information@2acaem9n.email.decathlon.fr\n" +
            "\n" +
            "infoswiifn@swiifnveritaspress.com\n" +
            "\n" +
            "invite@textplus.com\n" +
            "\n" +
            "ionusjc@email.mxgjzxh.org\n" +
            "\n" +
            "irs@service.govdelivery.com\n" +
            "\n" +
            "itworks@itworksglobal.com\n" +
            "\n" +
            "jampaper@lwtvpfmt.email.jampaper.com\n" +
            "\n" +
            "jane@8yc7emybee0f.janemayjones.com\n" +
            "\n" +
            "jim@primalsourcenews.com\n" +
            "\n" +
            "jonathans@mecloud.co.in\n" +
            "\n" +
            "kcranfill@ifxgv6ilz3.terrainrx.com\n" +
            "\n" +
            "kevin.konz@0vntpd3iwr.tractares.com\n" +
            "\n" +
            "kontakt@jjufrnwha.paintballsports.de\n" +
            "\n" +
            "marketing-gpcu@ff3sy1i07.gpcu.org\n" +
            "\n" +
            "marketing@ctwnlnmvw.linleyandsimpson.co.uk\n" +
            "\n" +
            "marketing@ufodk0l99.zcscompany.com\n" +
            "\n" +
            "mitcham@9clooqvlk.thesourcebulkfoods.com.au\n" +
            "\n" +
            "news@bfg3y7xwwybp.taipan.at\n" +
            "\n" +
            "news@tr1aqxgnt.see.me\n" +
            "\n" +
            "newsletter@fhxrqkm46.premierpokerchips.com\n" +
            "\n" +
            "niclaandyou@sgujw7phmj.nicla.com\n" +
            "\n" +
            "noreply@dzebigrzl.allyouplay.com\n" +
            "\n" +
            "office@jrfsby3v0g.eposcomputer.at\n" +
            "\n" +
            "office@tkfrkjkdbd.bodegarioja.at\n" +
            "\n" +
            "postit@aspernaturogyhs.calemero.club\n" +
            "\n" +
            "postit@atquexvpil.unicef-asia.com\n" +
            "\n" +
            "postit@autemiijgx.zhiliga.cloud\n" +
            "\n" +
            "postit@autemsyogw.unicef-asia.com\n" +
            "\n" +
            "postit@autemyhemf.persoluxure.com\n" +
            "\n" +
            "postit@beataepovps.persoluxure.com\n" +
            "\n" +
            "postit@consequaturofbrr.pfizerinc.org\n" +
            "\n" +
            "postit@consequaturozulp.resumain.shop\n" +
            "\n" +
            "postit@consequatursnzws.samabonga.info\n" +
            "\n" +
            "postit@contact-us.in\n" +
            "\n" +
            "postit@corporisllrga.speedns.wiki\n" +
            "\n" +
            "postit@corporisogflt.pfizerinc.org\n" +
            "\n" +
            "postit@cumaaqui.kismint.net\n" +
            "\n" +
            "postit@cupiditateuzipe.aragoza.blog\n" +
            "\n" +
            "postit@delectuspkgab.diskoverit.shop\n" +
            "\n" +
            "postit@dewmme.contact-us.in\n" +
            "\n" +
            "postit@dignissimoskdeex.hugevariety.cc\n" +
            "\n" +
            "postit@doloremckqiq.bullbassor.me\n" +
            "\n" +
            "postit@doloreskcbll.joebiden2020.me\n" +
            "\n" +
            "postit@doloreskowbe.unicef-asia.com\n" +
            "\n" +
            "postit@dolorumgurpe.kismint.net\n" +
            "\n" +
            "postit@egxatx.contact-us.in\n" +
            "\n" +
            "postit@eligendiamhai.kismint.net\n" +
            "\n" +
            "postit@eligendifrfiy.calemero.club\n" +
            "\n" +
            "postit@erroresjiu.pfizerinc.me\n" +
            "\n" +
            "postit@errorowmyc.resumain.shop\n" +
            "\n" +
            "postit@estbwhau.tofreeprivacy.com\n" +
            "\n" +
            "postit@estcmapo.aragoza.blog\n" +
            "\n" +
            "postit@estzovle.kismint.net\n" +
            "\n" +
            "postit@eumvdyas.pfizerinc.me\n" +
            "\n" +
            "postit@evenietkavtt.holydrops.blog\n" +
            "\n" +
            "postit@explicaboxybro.thornburg.de\n" +
            "\n" +
            "postit@fugitgrvjj.aragoza.blog\n" +
            "\n" +
            "postit@impeditqplbz.rightforyou.me\n" +
            "\n" +
            "postit@inventorepgsir.persoluxure.com\n" +
            "\n" +
            "postit@ipsumavrkk.persoluxure.com\n" +
            "\n" +
            "postit@jaktan.info\n" +
            "\n" +
            "postit@kismint.net\n" +
            "\n" +
            "postit@laudantiumogvvu.pfizerinc.me\n" +
            "\n" +
            "postit@liaown.contact-us.in\n" +
            "\n" +
            "postit@liberoqtbhk.transferitnow.org\n" +
            "\n" +
            "postit@magnamempjt.calemero.club\n" +
            "\n" +
            "postit@magnigmeun.tofreeprivacy.com\n" +
            "\n" +
            "postit@maximettigz.hugevariety.cc\n" +
            "\n" +
            "postit@maximeveuuj.pfizerinc.org\n" +
            "\n" +
            "postit@minimakxdyh.aragoza.blog\n" +
            "\n" +
            "postit@minusvxehu.hugevariety.cc\n" +
            "\n" +
            "postit@molestiaexvkyz.pfizerinc.me\n" +
            "\n" +
            "postit@necessitatibusuttyz.samabonga.info\n" +
            "\n" +
            "postit@nisivkpbd.kismint.net\n" +
            "\n" +
            "postit@occaecatipzxbi.pfizerinc.me\n" +
            "\n" +
            "postit@oditjlxzz.pfizerinc.me\n" +
            "\n" +
            "postit@oditsgort.kismint.net\n" +
            "\n" +
            "postit@officiawgvnz.unicef-asia.com\n" +
            "\n" +
            "postit@perspiciatisfbthm.samabonga.info\n" +
            "\n" +
            "postit@pfizerinc.org\n" +
            "\n" +
            "postit@pgljgz.jaktan.info\n" +
            "\n" +
            "postit@possimustbwdj.samabonga.info\n" +
            "\n" +
            "postit@quiazkeap.privacyguardhelp.com\n" +
            "\n" +
            "postit@quibrvbe.privacyguardhelp.com\n" +
            "\n" +
            "postit@quibusdamjpsok.pfizerinc.me\n" +
            "\n" +
            "postit@quibusdamwghzk.tofreeprivacy.com\n" +
            "\n" +
            "postit@quidemiuguw.privacyguardhelp.com\n" +
            "\n" +
            "postit@quidemjbfsh.samabonga.info\n" +
            "\n" +
            "postit@quidemoamjg.persoluxure.com\n" +
            "\n" +
            "postit@quissshjo.aragoza.blog\n" +
            "\n" +
            "postit@reiciendisxpvdo.tofreeprivacy.com\n" +
            "\n" +
            "postit@repellattzdmd.thornburg.de\n" +
            "\n" +
            "postit@resumain.shop\n" +
            "\n" +
            "postit@saepeylhfz.smartdrops.me\n" +
            "\n" +
            "postit@sedgkyvm.highvoldr.me\n" +
            "\n" +
            "postit@sintxintr.smartdrops.me\n" +
            "\n" +
            "postit@sitcppmf.unicef-asia.com\n" +
            "\n" +
            "postit@sitjtmia.regalkof.club\n" +
            "\n" +
            "postit@speedns.wiki\n" +
            "\n" +
            "postit@suscipitiljnu.resumain.shop\n" +
            "\n" +
            "postit@suscipitjhfrh.resumain.shop\n" +
            "\n" +
            "postit@tofreeprivacy.com\n" +
            "\n" +
            "postit@unicef-asia.com\n" +
            "\n" +
            "postit@uthjpsw.calemero.club\n" +
            "\n" +
            "postit@utnkvza.hugevariety.cc\n" +
            "\n" +
            "postit@veniamiuslx.pfizerinc.me\n" +
            "\n" +
            "postit@veritatisuwkhq.pfizerinc.me\n" +
            "\n" +
            "postit@vijoea.jaktan.info\n" +
            "\n" +
            "postit@voluptasgedsb.persoluxure.com\n" +
            "\n" +
            "postit@voluptatembglfy.builderinc.org\n" +
            "\n" +
            "postit@voluptatemrlhxj.holydrops.blog\n" +
            "\n" +
            "postit@vvrpyn.contact-us.in\n" +
            "\n" +
            "postmaster@mychway.com\n" +
            "\n" +
            "pr@tjskids.com\n" +
            "\n" +
            "prachisharmaseo@outlook.com\n" +
            "\n" +
            "praise_legrande484x782@hotmail.com\n" +
            "\n" +
            "press@2fgbmofq4.shots.it\n" +
            "\n" +
            "press@nbeqfkdch.antoniasautter.it\n" +
            "\n" +
            "presse@xgxyknqcvx.schloss-kaltenberg.de\n" +
            "\n" +
            "pressoffice@pt3maqcy9.luisabertoldo.com\n" +
            "\n" +
            "privacy@ppedbsxwg.bpress.it\n" +
            "\n" +
            "product-updates@boodpecker.co\n" +
            "\n" +
            "production@clothes2order.com\n" +
            "\n" +
            "promo@sabrinasiegl934.onmicrosoft.com\n" +
            "\n" +
            "promos@zagg.com\n" +
            "\n" +
            "promotions@pbxjrj.baltimore.aiga.org\n" +
            "\n" +
            "puritanspride@e.puritan.com\n" +
            "\n" +
            "qftpxgnmceyukxq-rcfxz-yarvxxilhztwjif@bateriesh.com\n" +
            "\n" +
            "qgmc@email.czaa.org\n" +
            "\n" +
            "quynhanh10072012@gmail.com\n" +
            "\n" +
            "qvc@nkrv.onmicrosoft.com\n" +
            "\n" +
            "qvprjb.xuplrwi@hvbrxvmwst.perrychristinejacobs.work\n" +
            "\n" +
            "raolson@staylocalsavebig.biz\n" +
            "\n" +
            "raquel@temporadalivre.com\n" +
            "\n" +
            "reasonalert@aakxm.e.reason.org\n" +
            "\n" +
            "redactie@yt0ikodyha9j.vvn.nl\n" +
            "\n" +
            "registrar@negrelli9c.onmicrosoft.com\n" +
            "\n" +
            "reply@email.harmandio.com\n" +
            "\n" +
            "reply@fpktmr.email.games.sonypictures.com\n" +
            "\n" +
            "reply@ho8i1hoiwa7n.parkettart.com\n" +
            "\n" +
            "reply@oczouc.uq.uniqlo.com.sg\n" +
            "\n" +
            "reply@shmgcw.marketing.rodanandfields.com\n" +
            "\n" +
            "reply@ufkixyvu.news.legacy.com\n" +
            "\n" +
            "reply@undamn.finantages.com\n" +
            "\n" +
            "reservations@7x9sfouv5.flysolomons.com\n" +
            "\n" +
            "retif.espana@ouall.n.retif.eu\n" +
            "\n" +
            "rewards@bjerggrethe.onmicrosoft.com\n" +
            "\n" +
            "rhybgkk@email.avkgulw.org\n" +
            "\n" +
            "routledgebooks@nxhz8td.email.routledge.com\n" +
            "\n" +
            "rqruzuh@email.gnzjhsw.org\n" +
            "\n" +
            "rwavgf7oxfn3y5l-wzcoelv0hhvchzvn@googlegroups.com\n" +
            "\n" +
            "ryan@lovejoywellness.biz\n" +
            "\n" +
            "ryan@lovejoywellness.net\n" +
            "\n" +
            "saksfifthavenue@news.saks.com\n" +
            "\n" +
            "sal@k0ucov0e.zitigreetings.com\n" +
            "\n" +
            "salem@vampfangs.com\n" +
            "\n" +
            "sales@6z9zkrgan.designedcolour.com\n" +
            "\n" +
            "sales@grosssu6.onmicrosoft.com\n" +
            "\n" +
            "sales@mjbcis5itrxt.third-reich-posters.co.uk\n" +
            "\n" +
            "sales@nadinegrab55.onmicrosoft.com\n" +
            "\n" +
            "sales@silverprint.co.uk\n" +
            "\n" +
            "sales@theprintcompany.co.za\n" +
            "\n" +
            "sales@wilkinson.co.uk\n" +
            "\n" +
            "sales@xeiodd1.akpress.org\n" +
            "\n" +
            "sallybeauty@zovj9e.em.sallybeauty.com\n" +
            "\n" +
            "salzgitter-lebenstedt@dbklty.easyfitness.club\n" +
            "\n" +
            "sara@bqbhwnblz.costaricafilmsupport.com\n" +
            "\n" +
            "scooteedeals@cl9qgg.promotion.flyscoot.com\n" +
            "\n" +
            "scott@yunnansourcing.com\n" +
            "\n" +
            "sculthorpe@hd4agywfv.hawkandowl.org\n" +
            "\n" +
            "seawolves@seawolves.com\n" +
            "\n" +
            "seguridad@caixabankia.com\n" +
            "\n" +
            "selezione@oggilavoro.eu\n" +
            "\n" +
            "send@crownawardsmarketing.com\n" +
            "\n" +
            "sender@maverickcrm.com\n" +
            "\n" +
            "service@hairfreesales.com\n" +
            "\n" +
            "seudinheiro@bw5obavsxbc9.mail1.seudinheiro.com\n" +
            "\n" +
            "shannon@email.starexpanses.com\n" +
            "\n" +
            "shop@men24x7.com\n" +
            "\n" +
            "shop@salsalzb.onmicrosoft.com\n" +
            "\n" +
            "shows@d2p.com\n" +
            "\n" +
            "simon@bytsmgccw.uptonsbutchers.co.uk\n" +
            "\n" +
            "sjhqvyz@email.mizetrd.org\n" +
            "\n" +
            "sketchup@03lue7idu.sketchup.com\n" +
            "\n" +
            "social@8kr2ch.vincon.com\n" +
            "\n" +
            "social@9dv81v7t6.50topitaly.it\n" +
            "\n" +
            "sofia@acedibles.com\n" +
            "\n" +
            "soin@xypztzpvd.kerali.fr\n" +
            "\n" +
            "song@of-the-day.com\n" +
            "\n" +
            "store-news@app12.app4stronew.in\n" +
            "\n" +
            "store-news@app12.filmypro.in\n" +
            "\n" +
            "store-news@app13.filmypro.in\n" +
            "\n" +
            "store-news@dealsofyou.com\n" +
            "\n" +
            "store-news@filmyglobal.com\n" +
            "\n" +
            "store-news@painale.com\n" +
            "\n" +
            "store-news@worldbestbuys.com\n" +
            "\n" +
            "store88t9gp@88t9gpoldearth.calderdale.sch.uk\n" +
            "\n" +
            "storeafdgnr@afdgnrmgsh.net\n" +
            "\n" +
            "storeatgouz@atgouzhaloasisminnesota.com\n" +
            "\n" +
            "storebyrkhq@byrkhqjsms.pe\n" +
            "\n" +
            "storeejnwgv@ejnwgvlezzi.info\n" +
            "\n" +
            "storeensmkj@ensmkjstabcps.uk\n" +
            "\n" +
            "storekv7kid@kv7kidtripleselpaso.com\n" +
            "\n" +
            "stores@0qztvahanoverautomotive.co.nz\n" +
            "\n" +
            "stores@oqnqw4hikari.co.nz\n" +
            "\n" +
            "style@badcock.email\n" +
            "\n" +
            "subscription.service@dubscriptions.dsa.gov\n" +
            "\n" +
            "suporte@xrnomoaqv.gondimconsultoria.com.br\n" +
            "\n" +
            "support@alianhost.com\n" +
            "\n" +
            "support@bichler454.onmicrosoft.com\n" +
            "\n" +
            "support@businessteam.iabmr.sensekey.biz\n" +
            "\n" +
            "support@ceribel.skinfactorymanagementstips.org.uk\n" +
            "\n" +
            "support@chandelierlighting.co.uk\n" +
            "\n" +
            "support@dtfr.hyuodfifg.click\n" +
            "\n" +
            "support@dulzbj.vitality4life.de\n" +
            "\n" +
            "support@gbosses.co.uk\n" +
            "\n" +
            "support@grssgst96.onmicrosoft.com\n" +
            "\n" +
            "support@he5rqejc.abiattachments.com\n" +
            "\n" +
            "support@kampst6.onmicrosoft.com\n" +
            "\n" +
            "support@kwhwitgx9.me-events.de\n" +
            "\n" +
            "support@metamask.shoes\n" +
            "\n" +
            "support@moonfight.co.uk\n" +
            "\n" +
            "support@nawex6lgyiy9.ajsports.ca\n" +
            "\n" +
            "support@nw.superdescuentos.eu\n" +
            "\n" +
            "support@startselect.com\n" +
            "\n" +
            "support@stickergiant.com\n" +
            "\n" +
            "support@znld.contentmo.com\n" +
            "\n" +
            "supporthqvu@hqvuaxconnect.com\n" +
            "\n" +
            "supportogka@ogkaaxconnect.com\n" +
            "\n" +
            "survey@quoyojrn.chakhda.net\n" +
            "\n" +
            "surveys@marlenraun.onmicrosoft.com\n" +
            "\n" +
            "susanne@hbqqmc.meinbaby123.de\n" +
            "\n" +
            "suupport@alianhost.com\n" +
            "\n" +
            "svage@enimayvvr.highvoldr.me\n" +
            "\n" +
            "sven@rapidmail.com\n" +
            "\n" +
            "sylviamccoskey1999@hotmail.com\n" +
            "\n" +
            "talktoace@express.medallia.com\n" +
            "\n" +
            "tanvihegde1@outlook.com\n" +
            "\n" +
            "team09@elsecore.info\n" +
            "\n" +
            "team@jlcolfag.email.worldwiderecession.net\n" +
            "\n" +
            "team@nyib.conda.at\n" +
            "\n" +
            "team@pqgcz9eq.mail.fite.tv\n" +
            "\n" +
            "teatroreal@rhxxcl.mail.teatroreal.es\n" +
            "\n" +
            "tech@maioresjmekl.joebiden2020.me\n" +
            "\n" +
            "tech@placeatuliih.joebiden2020.me\n" +
            "\n" +
            "teethkits@homeinsiderz.com\n" +
            "\n" +
            "tim@wtd3t1f1c.dinkysite.com\n" +
            "\n" +
            "tima772017@gmail.com\n" +
            "\n" +
            "titlenine@oxtpks.email.titlenine.com\n" +
            "\n" +
            "tlglexingtoneastky@thelittlegym.com\n" +
            "\n" +
            "tom@uurhn928xh.littletouches.com\n" +
            "\n" +
            "traian.iliescu@phys.ubbcluj.ro\n" +
            "\n" +
            "training@s5ubj2woj.yourpropertynetwork.co.uk\n" +
            "\n" +
            "tvpzykfrivgduntomqwgozmsjwf@infory.org\n" +
            "\n" +
            "tvuffvvoqhmicsfm8ggifk8ev@messaggi.immobiliare.it\n" +
            "\n" +
            "twqhdkc@email.knmepeb.org\n" +
            "\n" +
            "tylertool@emails.tylertool.com\n" +
            "\n" +
            "umjxobh@email.ohplsmy.org\n" +
            "\n" +
            "underarmour@emails.underarmour.com\n" +
            "\n" +
            "update@msf1a.email.flixbus.com\n" +
            "\n" +
            "updates@internationalmedicalcorps.org\n" +
            "\n" +
            "ursula.dahmen@imffourzyoxe.skynet.be\n" +
            "\n" +
            "uwjcfep@email.jznjmyr.org\n" +
            "\n" +
            "uypuos9fzi@nhlrr.5hsx.yabby.co.uk\n" +
            "\n" +
            "val@engagebay.co\n" +
            "\n" +
            "vanshikasharmaseo@outlook.com\n" +
            "\n" +
            "verify@databeamcenter.com\n" +
            "\n" +
            "videoland@dture.services.videoland.nl\n" +
            "\n" +
            "visitscotland@emails.visitscotland.com\n" +
            "\n" +
            "vlxou5mlac@wmyi.swartzbois.com\n" +
            "\n" +
            "volunteer@marckapeller35.onmicrosoft.com\n" +
            "\n" +
            "volunteer@nhsresponders.co.uk\n" +
            "\n" +
            "warehouse@5ul6n7wm2.hookedongranite.com\n" +
            "\n" +
            "webmaster@rtmterphsiky.ucppe.org\n" +
            "\n" +
            "webmaster@vhtpq7d2n.speedgraphic.co.uk\n" +
            "\n" +
            "webms@email.gsua.org\n" +
            "\n" +
            "webms@email.memw.org\n" +
            "\n" +
            "webms@email.qjzp.org\n" +
            "\n" +
            "webms@email.rgcf.org\n" +
            "\n" +
            "webms@email.zpfh.org\n" +
            "\n" +
            "webshop@augustindom55.onmicrosoft.com\n" +
            "\n" +
            "websiteservice@outlook.com\n" +
            "\n" +
            "wecare@soderbergsflorist.com\n" +
            "\n" +
            "wharton@yourf5oy.info.emeritus.org\n" +
            "\n" +
            "wifi@injhqyf.highvoldr.me\n" +
            "\n" +
            "wifi@possimusefman.ourfriends.me\n" +
            "\n" +
            "williamssonoma@kevinokab25.onmicrosoft.com\n" +
            "\n" +
            "windscribe785accet96braind310donhij@speedsearch2u.co.uk\n" +
            "\n" +
            "winterdubbelhtc@u1bjr2n.elliotampbell.co.uk\n" +
            "\n" +
            "wlkt@email.iheart.com\n" +
            "\n" +
            "workngear@btahincnglt.kochiy.me\n" +
            "\n" +
            "wpsoffices@maxwar.info\n" +
            "\n" +
            "xbhfqrafzwkonmb-zyrqd-zdjvbsmgfkpwevx@conectarais.org\n" +
            "\n" +
            "xhumroc@email.cvzsuag.org\n" +
            "\n" +
            "xojwafl@email.sfgmxfs.org\n" +
            "\n" +
            "xrbxptb@email.rczlurv.org\n" +
            "\n" +
            "xvgjmwc@email.hxbnath.org\n" +
            "\n" +
            "yakir@pluwrg.cloudinary.com\n" +
            "\n" +
            "yarnspirations@email.yarnspirations.com\n" +
            "\n" +
            "yorksandhumber@xelnh63zd.mail.nasuwt.org.uk\n" +
            "\n" +
            "your.friends@news.bankrate.com\n" +
            "\n" +
            "yours@praesentiumjalkc.pfizerinc.me\n" +
            "\n" +
            "yours@sedlfvnx.calemero.club\n" +
            "\n" +
            "ypjffrmyby7nr7p-sikzt29fnoqlbbps@googlegroups.com\n" +
            "\n" +
            "ysamovr@email.xfdcwkv.org\n" +
            "\n" +
            "yvplzcx@email.ofgtxjp.org\n" +
            "\n" +
            "yzhjsor@email.wpyagtm.org\n" +
            "\n" +
            "zales@em.zales.com\n" +
            "\n" +
            "zbanuyv@email.tkkkmtv.org\n" +
            "\n" +
            "zhrntre@email.qxbxovi.org\n" +
            "\n" +
            "zina@eoosend.com\n" +
            "\n" +
            "zznews@newsletter.zzounds.com\n" +
            "zznews@q5gfe.11st.co.kr").split("\n\n");


}
